//// tabler · outline · shard "i". GENERATED by gg_icon_gen — do not hand-edit.

import gg_icon/icon
import gg_icons_tabler/internal
import lustre/attribute.{type Attribute}
import lustre/element.{type Element}
import lustre/element/svg

/// `ice-cream`
pub fn ice_cream(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([attribute.attribute("d", "M12 21.5v-4.5")]),
      svg.path([attribute.attribute("d", "M8 17h8v-10a4 4 0 1 0 -8 0v10")]),
      svg.path([attribute.attribute("d", "M8 10.5l8 -3.5")]),
      svg.path([attribute.attribute("d", "M8 14.5l8 -3.5")]),
    ],
  )
}

/// `ice-cream-2`
pub fn ice_cream_2(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([attribute.attribute("d", "M17.657 11a6 6 0 1 0 -11.315 0")]),
      svg.path([
        attribute.attribute("d", "M6.342 11l5.658 11l5.657 -11l-11.315 0"),
      ]),
    ],
  )
}

/// `ice-cream-off`
pub fn ice_cream_off(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([attribute.attribute("d", "M12 21.5v-4.5")]),
      svg.path([
        attribute.attribute("d", "M8 8v9h8v-1m0 -4v-5a4 4 0 0 0 -7.277 -2.294"),
      ]),
      svg.path([
        attribute.attribute("d", "M8 10.5l1.74 -.76m2.79 -1.222l3.47 -1.518"),
      ]),
      svg.path([attribute.attribute("d", "M8 14.5l4.488 -1.964")]),
      svg.path([attribute.attribute("d", "M3 3l18 18")]),
    ],
  )
}

/// `ice-skating`
pub fn ice_skating(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([
        attribute.attribute(
          "d",
          "M5.905 5h3.418a1 1 0 0 1 .928 .629l1.143 2.856a3 3 0 0 0 2.207 1.83l4.717 .926a2.084 2.084 0 0 1 1.682 2.045v.714a1 1 0 0 1 -1 1h-13.895a1 1 0 0 1 -1 -1.1l.8 -8a1 1 0 0 1 1 -.9",
        ),
      ]),
      svg.path([attribute.attribute("d", "M3 19h17a1 1 0 0 0 1 -1")]),
      svg.path([attribute.attribute("d", "M9 15v4")]),
      svg.path([attribute.attribute("d", "M15 15v4")]),
    ],
  )
}

/// `iceberg`
pub fn iceberg(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([
        attribute.attribute(
          "d",
          "M19 10l-2 9l-4 3l-3 -5l-3 -1l-2 -6l2 -5l3 -2l3 3l4 1l2 3",
        ),
      ]),
      svg.path([attribute.attribute("d", "M3 10h18")]),
    ],
  )
}

/// `icons`
pub fn icons(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([
        attribute.attribute("d", "M3 6.5a3.5 3.5 0 1 0 7 0a3.5 3.5 0 1 0 -7 0"),
      ]),
      svg.path([attribute.attribute("d", "M2.5 21h8l-4 -7l-4 7")]),
      svg.path([attribute.attribute("d", "M14 3l7 7")]),
      svg.path([attribute.attribute("d", "M14 10l7 -7")]),
      svg.path([attribute.attribute("d", "M14 14h7v7h-7l0 -7")]),
    ],
  )
}

/// `icons-off`
pub fn icons_off(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([
        attribute.attribute(
          "d",
          "M4.01 4.041a3.5 3.5 0 0 0 2.49 5.959c.975 0 1.865 -.357 2.5 -1m.958 -3.044a3.503 3.503 0 0 0 -2.905 -2.912",
        ),
      ]),
      svg.path([attribute.attribute("d", "M2.5 21h8l-4 -7l-4 7")]),
      svg.path([attribute.attribute("d", "M14 3l7 7")]),
      svg.path([attribute.attribute("d", "M14 10l7 -7")]),
      svg.path([attribute.attribute("d", "M18 14h3v3m0 4h-7v-7")]),
      svg.path([attribute.attribute("d", "M3 3l18 18")]),
    ],
  )
}

/// `id`
pub fn id(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([
        attribute.attribute(
          "d",
          "M3 7a3 3 0 0 1 3 -3h12a3 3 0 0 1 3 3v10a3 3 0 0 1 -3 3h-12a3 3 0 0 1 -3 -3l0 -10",
        ),
      ]),
      svg.path([attribute.attribute("d", "M7 10a2 2 0 1 0 4 0a2 2 0 1 0 -4 0")]),
      svg.path([attribute.attribute("d", "M15 8l2 0")]),
      svg.path([attribute.attribute("d", "M15 12l2 0")]),
      svg.path([attribute.attribute("d", "M7 16l10 0")]),
    ],
  )
}

/// `id-badge`
pub fn id_badge(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([
        attribute.attribute(
          "d",
          "M5 6a3 3 0 0 1 3 -3h8a3 3 0 0 1 3 3v12a3 3 0 0 1 -3 3h-8a3 3 0 0 1 -3 -3l0 -12",
        ),
      ]),
      svg.path([attribute.attribute("d", "M10 13a2 2 0 1 0 4 0a2 2 0 1 0 -4 0")]),
      svg.path([attribute.attribute("d", "M10 6h4")]),
      svg.path([attribute.attribute("d", "M9 18h6")]),
    ],
  )
}

/// `id-badge-2`
pub fn id_badge_2(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([attribute.attribute("d", "M7 12h3v4h-3l0 -4")]),
      svg.path([
        attribute.attribute(
          "d",
          "M10 6h-6a1 1 0 0 0 -1 1v12a1 1 0 0 0 1 1h16a1 1 0 0 0 1 -1v-12a1 1 0 0 0 -1 -1h-6",
        ),
      ]),
      svg.path([
        attribute.attribute(
          "d",
          "M10 4a1 1 0 0 1 1 -1h2a1 1 0 0 1 1 1v3a1 1 0 0 1 -1 1h-2a1 1 0 0 1 -1 -1l0 -3",
        ),
      ]),
      svg.path([attribute.attribute("d", "M14 16h2")]),
      svg.path([attribute.attribute("d", "M14 12h4")]),
    ],
  )
}

/// `id-badge-off`
pub fn id_badge_off(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([
        attribute.attribute(
          "d",
          "M7.141 3.125a3 3 0 0 1 .859 -.125h8a3 3 0 0 1 3 3v9m-.13 3.874a3 3 0 0 1 -2.87 2.126h-8a3 3 0 0 1 -3 -3v-12a3 3 0 0 1 .128 -.869",
        ),
      ]),
      svg.path([
        attribute.attribute("d", "M11.179 11.176a2 2 0 1 0 2.635 2.667"),
      ]),
      svg.path([attribute.attribute("d", "M10 6h4")]),
      svg.path([attribute.attribute("d", "M9 18h6")]),
      svg.path([attribute.attribute("d", "M3 3l18 18")]),
    ],
  )
}

/// `id-off`
pub fn id_off(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([
        attribute.attribute(
          "d",
          "M8 4h10a3 3 0 0 1 3 3v10m-1.437 2.561c-.455 .279 -.99 .439 -1.563 .439h-12a3 3 0 0 1 -3 -3v-10c0 -1.083 .573 -2.031 1.433 -2.559",
        ),
      ]),
      svg.path([attribute.attribute("d", "M8.175 8.178a2 2 0 1 0 2.646 2.65")]),
      svg.path([attribute.attribute("d", "M15 8h2")]),
      svg.path([attribute.attribute("d", "M16 12h1")]),
      svg.path([attribute.attribute("d", "M7 16h9")]),
      svg.path([attribute.attribute("d", "M3 3l18 18")]),
    ],
  )
}

/// `ikosaedr`
pub fn ikosaedr(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([
        attribute.attribute(
          "d",
          "M21 8.007v7.986a2 2 0 0 1 -1.006 1.735l-7 4.007a2 2 0 0 1 -1.988 0l-7 -4.007a2 2 0 0 1 -1.006 -1.735v-7.986a2 2 0 0 1 1.006 -1.735l7 -4.007a2 2 0 0 1 1.988 0l7 4.007a2 2 0 0 1 1.006 1.735",
        ),
      ]),
      svg.path([attribute.attribute("d", "M3.29 6.97l4.21 2.03")]),
      svg.path([attribute.attribute("d", "M20.71 6.97l-4.21 2.03")]),
      svg.path([attribute.attribute("d", "M20.7 17h-17.4")]),
      svg.path([attribute.attribute("d", "M11.76 2.03l-4.26 6.97l-4.3 7.84")]),
      svg.path([
        attribute.attribute("d", "M12.24 2.03q 2.797 4.44 4.26 6.97t 4.3 7.84"),
      ]),
      svg.path([attribute.attribute("d", "M12 17l-4.5 -8h9l-4.5 8")]),
      svg.path([attribute.attribute("d", "M12 17v5")]),
    ],
  )
}

/// `image-generation`
pub fn image_generation(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([attribute.attribute("d", "M3 21v-4a4 4 0 1 1 4 4h-4")]),
      svg.path([attribute.attribute("d", "M21 3a16 16 0 0 0 -12.8 10.2")]),
      svg.path([attribute.attribute("d", "M21 3a16 16 0 0 1 -10.2 12.8")]),
      svg.path([attribute.attribute("d", "M10.6 9a9 9 0 0 1 4.4 4.4")]),
      svg.path([
        attribute.attribute(
          "d",
          "M17 19a2 2 0 0 1 2 2a2 2 0 0 1 2 -2a2 2 0 0 1 -2 -2a2 2 0 0 1 -2 2",
        ),
      ]),
      svg.path([
        attribute.attribute(
          "d",
          "M3 5a2 2 0 0 1 2 2a2 2 0 0 1 2 -2a2 2 0 0 1 -2 -2a2 2 0 0 1 -2 2",
        ),
      ]),
    ],
  )
}

/// `image-in-picture`
pub fn image_in_picture(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([attribute.attribute("d", "M13 15c-2 0 -5 1 -5 5")]),
      svg.path([
        attribute.attribute(
          "d",
          "M4 13a2 2 0 0 1 2 -2h5a2 2 0 0 1 2 2v5a2 2 0 0 1 -2 2h-5a2 2 0 0 1 -2 -2l0 -5",
        ),
      ]),
      svg.path([attribute.attribute("d", "M4 7v-2a1 1 0 0 1 1 -1h2")]),
      svg.path([attribute.attribute("d", "M11 4h2")]),
      svg.path([attribute.attribute("d", "M17 4h2a1 1 0 0 1 1 1v2")]),
      svg.path([attribute.attribute("d", "M20 11v2")]),
      svg.path([attribute.attribute("d", "M20 17v2a1 1 0 0 1 -1 1h-2")]),
    ],
  )
}

/// `inbox`
pub fn inbox(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([
        attribute.attribute(
          "d",
          "M4 6a2 2 0 0 1 2 -2h12a2 2 0 0 1 2 2v12a2 2 0 0 1 -2 2h-12a2 2 0 0 1 -2 -2l0 -12",
        ),
      ]),
      svg.path([attribute.attribute("d", "M4 13h3l3 3h4l3 -3h3")]),
    ],
  )
}

/// `inbox-off`
pub fn inbox_off(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([
        attribute.attribute(
          "d",
          "M8 4h10a2 2 0 0 1 2 2v10m-.593 3.422a2 2 0 0 1 -1.407 .578h-12a2 2 0 0 1 -2 -2v-12c0 -.554 .225 -1.056 .59 -1.418",
        ),
      ]),
      svg.path([
        attribute.attribute("d", "M4 13h3l3 3h4l.987 -.987m2.013 -2.013h3"),
      ]),
      svg.path([attribute.attribute("d", "M3 3l18 18")]),
    ],
  )
}

/// `indent-decrease`
pub fn indent_decrease(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([attribute.attribute("d", "M20 6l-7 0")]),
      svg.path([attribute.attribute("d", "M20 12l-9 0")]),
      svg.path([attribute.attribute("d", "M20 18l-7 0")]),
      svg.path([attribute.attribute("d", "M8 8l-4 4l4 4")]),
    ],
  )
}

/// `indent-increase`
pub fn indent_increase(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([attribute.attribute("d", "M20 6l-11 0")]),
      svg.path([attribute.attribute("d", "M20 12l-7 0")]),
      svg.path([attribute.attribute("d", "M20 18l-11 0")]),
      svg.path([attribute.attribute("d", "M4 8l4 4l-4 4")]),
    ],
  )
}

/// `infinity`
pub fn infinity(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([
        attribute.attribute(
          "d",
          "M9.828 9.172a4 4 0 1 0 0 5.656a10 10 0 0 0 2.172 -2.828a10 10 0 0 1 2.172 -2.828a4 4 0 1 1 0 5.656a10 10 0 0 1 -2.172 -2.828a10 10 0 0 0 -2.172 -2.828",
        ),
      ]),
    ],
  )
}

/// `infinity-2`
pub fn infinity_2(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([
        attribute.attribute(
          "d",
          "M13.94 9.39a10 10 0 0 1 .232 -.218a4 4 0 1 1 0 5.656a10 10 0 0 1 -2.172 -2.828a10 10 0 0 0 -2.172 -2.828a4 4 0 1 0 0 5.656a10 10 0 0 0 .234 -.219",
        ),
      ]),
    ],
  )
}

/// `infinity-off`
pub fn infinity_off(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([
        attribute.attribute(
          "d",
          "M8.165 8.174a4 4 0 0 0 -5.166 3.826a4 4 0 0 0 6.829 2.828a10 10 0 0 0 2.172 -2.828m1.677 -2.347a10 10 0 0 1 .495 -.481a4 4 0 1 1 5.129 6.1m-3.521 .537a4 4 0 0 1 -1.608 -.981a10 10 0 0 1 -2.172 -2.828",
        ),
      ]),
      svg.path([attribute.attribute("d", "M3 3l18 18")]),
    ],
  )
}

/// `info-circle`
pub fn info_circle(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([
        attribute.attribute("d", "M3 12a9 9 0 1 0 18 0a9 9 0 0 0 -18 0"),
      ]),
      svg.path([attribute.attribute("d", "M12 9h.01")]),
      svg.path([attribute.attribute("d", "M11 12h1v4h1")]),
    ],
  )
}

/// `info-hexagon`
pub fn info_hexagon(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([
        attribute.attribute(
          "d",
          "M19.875 6.27c.7 .398 1.13 1.143 1.125 1.948v7.284c0 .809 -.443 1.555 -1.158 1.948l-6.75 4.27a2.269 2.269 0 0 1 -2.184 0l-6.75 -4.27a2.225 2.225 0 0 1 -1.158 -1.948v-7.285c0 -.809 .443 -1.554 1.158 -1.947l6.75 -3.98a2.33 2.33 0 0 1 2.25 0l6.75 3.98h-.033",
        ),
      ]),
      svg.path([attribute.attribute("d", "M12 9h.01")]),
      svg.path([attribute.attribute("d", "M11 12h1v4h1")]),
    ],
  )
}

/// `info-octagon`
pub fn info_octagon(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([
        attribute.attribute(
          "d",
          "M12.802 2.165l5.575 2.389c.48 .206 .863 .589 1.07 1.07l2.388 5.574c.22 .512 .22 1.092 0 1.604l-2.389 5.575c-.206 .48 -.589 .863 -1.07 1.07l-5.574 2.388c-.512 .22 -1.092 .22 -1.604 0l-5.575 -2.389a2.036 2.036 0 0 1 -1.07 -1.07l-2.388 -5.574a2.036 2.036 0 0 1 0 -1.604l2.389 -5.575c.206 -.48 .589 -.863 1.07 -1.07l5.574 -2.388a2.036 2.036 0 0 1 1.604 0",
        ),
      ]),
      svg.path([attribute.attribute("d", "M12 9h.01")]),
      svg.path([attribute.attribute("d", "M11 12h1v4h1")]),
    ],
  )
}

/// `info-small`
pub fn info_small(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([attribute.attribute("d", "M12 9h.01")]),
      svg.path([attribute.attribute("d", "M11 12h1v4h1")]),
    ],
  )
}

/// `info-square`
pub fn info_square(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([attribute.attribute("d", "M12 9h.01")]),
      svg.path([
        attribute.attribute(
          "d",
          "M3 5a2 2 0 0 1 2 -2h14a2 2 0 0 1 2 2v14a2 2 0 0 1 -2 2h-14a2 2 0 0 1 -2 -2v-14",
        ),
      ]),
      svg.path([attribute.attribute("d", "M11 12h1v4h1")]),
    ],
  )
}

/// `info-square-rounded`
pub fn info_square_rounded(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([attribute.attribute("d", "M12 9h.01")]),
      svg.path([attribute.attribute("d", "M11 12h1v4h1")]),
      svg.path([
        attribute.attribute(
          "d",
          "M12 3c7.2 0 9 1.8 9 9c0 7.2 -1.8 9 -9 9c-7.2 0 -9 -1.8 -9 -9c0 -7.2 1.8 -9 9 -9",
        ),
      ]),
    ],
  )
}

/// `info-triangle`
pub fn info_triangle(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([
        attribute.attribute(
          "d",
          "M10.363 3.591l-8.106 13.534a1.914 1.914 0 0 0 1.636 2.871h16.214a1.914 1.914 0 0 0 1.636 -2.87l-8.106 -13.536a1.914 1.914 0 0 0 -3.274 0",
        ),
      ]),
      svg.path([attribute.attribute("d", "M12 9h.01")]),
      svg.path([attribute.attribute("d", "M11 12h1v4h1")]),
    ],
  )
}

/// `inner-shadow-bottom`
pub fn inner_shadow_bottom(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([
        attribute.attribute(
          "d",
          "M18.364 18.364a9 9 0 1 0 -12.728 -12.728a9 9 0 0 0 12.728 12.728",
        ),
      ]),
      svg.path([attribute.attribute("d", "M7.757 16.243a6 6 0 0 0 8.486 0")]),
    ],
  )
}

/// `inner-shadow-bottom-left`
pub fn inner_shadow_bottom_left(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([
        attribute.attribute("d", "M3 12a9 9 0 1 0 18 0a9 9 0 1 0 -18 0"),
      ]),
      svg.path([attribute.attribute("d", "M6 12a6 6 0 0 0 6 6")]),
    ],
  )
}

/// `inner-shadow-bottom-right`
pub fn inner_shadow_bottom_right(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([
        attribute.attribute("d", "M12 21a9 9 0 1 1 0 -18a9 9 0 0 1 0 18"),
      ]),
      svg.path([attribute.attribute("d", "M18 12a6 6 0 0 1 -6 6")]),
    ],
  )
}

/// `inner-shadow-left`
pub fn inner_shadow_left(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([
        attribute.attribute(
          "d",
          "M5.636 5.636a9 9 0 1 1 12.728 12.728a9 9 0 0 1 -12.728 -12.728",
        ),
      ]),
      svg.path([attribute.attribute("d", "M7.757 16.243a6 6 0 0 1 0 -8.486")]),
    ],
  )
}

/// `inner-shadow-right`
pub fn inner_shadow_right(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([
        attribute.attribute(
          "d",
          "M18.364 18.364a9 9 0 1 1 -12.728 -12.728a9 9 0 0 1 12.728 12.728",
        ),
      ]),
      svg.path([attribute.attribute("d", "M16.243 7.757a6 6 0 0 1 0 8.486")]),
    ],
  )
}

/// `inner-shadow-top`
pub fn inner_shadow_top(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([
        attribute.attribute(
          "d",
          "M5.636 5.636a9 9 0 1 0 12.728 12.728a9 9 0 0 0 -12.728 -12.728",
        ),
      ]),
      svg.path([attribute.attribute("d", "M16.243 7.757a6 6 0 0 0 -8.486 0")]),
    ],
  )
}

/// `inner-shadow-top-left`
pub fn inner_shadow_top_left(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([
        attribute.attribute("d", "M12 3a9 9 0 1 1 0 18a9 9 0 0 1 0 -18"),
      ]),
      svg.path([attribute.attribute("d", "M6 12a6 6 0 0 1 6 -6")]),
    ],
  )
}

/// `inner-shadow-top-right`
pub fn inner_shadow_top_right(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([
        attribute.attribute("d", "M12 3a9 9 0 1 0 0 18a9 9 0 0 0 0 -18"),
      ]),
      svg.path([attribute.attribute("d", "M18 12a6 6 0 0 0 -6 -6")]),
    ],
  )
}

/// `input-ai`
pub fn input_ai(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([
        attribute.attribute(
          "d",
          "M20 11v-2a2 2 0 0 0 -2 -2h-12a2 2 0 0 0 -2 2v5a2 2 0 0 0 2 2h4",
        ),
      ]),
      svg.path([attribute.attribute("d", "M14 21v-4a2 2 0 1 1 4 0v4")]),
      svg.path([attribute.attribute("d", "M14 19h4")]),
      svg.path([attribute.attribute("d", "M21 15v6")]),
    ],
  )
}

/// `input-check`
pub fn input_check(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([
        attribute.attribute(
          "d",
          "M20 13v-4a2 2 0 0 0 -2 -2h-12a2 2 0 0 0 -2 2v5a2 2 0 0 0 2 2h6",
        ),
      ]),
      svg.path([attribute.attribute("d", "M15 19l2 2l4 -4")]),
    ],
  )
}

/// `input-search`
pub fn input_search(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([
        attribute.attribute(
          "d",
          "M20 11v-2a2 2 0 0 0 -2 -2h-12a2 2 0 0 0 -2 2v5a2 2 0 0 0 2 2h5",
        ),
      ]),
      svg.path([attribute.attribute("d", "M15 18a3 3 0 1 0 6 0a3 3 0 1 0 -6 0")]),
      svg.path([attribute.attribute("d", "M20.2 20.2l1.8 1.8")]),
    ],
  )
}

/// `input-spark`
pub fn input_spark(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([
        attribute.attribute(
          "d",
          "M19 22.5a4.75 4.75 0 0 1 3.5 -3.5a4.75 4.75 0 0 1 -3.5 -3.5a4.75 4.75 0 0 1 -3.5 3.5a4.75 4.75 0 0 1 3.5 3.5",
        ),
      ]),
      svg.path([
        attribute.attribute(
          "d",
          "M20 11.5v-2.5a2 2 0 0 0 -2 -2h-12a2 2 0 0 0 -2 2v5a2 2 0 0 0 2 2h7",
        ),
      ]),
    ],
  )
}

/// `input-x`
pub fn input_x(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([
        attribute.attribute(
          "d",
          "M20 13v-4a2 2 0 0 0 -2 -2h-12a2 2 0 0 0 -2 2v5a2 2 0 0 0 2 2h7",
        ),
      ]),
      svg.path([attribute.attribute("d", "M22 22l-5 -5")]),
      svg.path([attribute.attribute("d", "M17 22l5 -5")]),
    ],
  )
}

/// `invoice`
pub fn invoice(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([attribute.attribute("d", "M14 3v4a1 1 0 0 0 1 1h4")]),
      svg.path([
        attribute.attribute(
          "d",
          "M19 12v7a1.78 1.78 0 0 1 -3.1 1.4a1.65 1.65 0 0 0 -2.6 0a1.65 1.65 0 0 1 -2.6 0a1.65 1.65 0 0 0 -2.6 0a1.78 1.78 0 0 1 -3.1 -1.4v-14a2 2 0 0 1 2 -2h7l5 5v4.25",
        ),
      ]),
    ],
  )
}

/// `ironing`
pub fn ironing(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([
        attribute.attribute(
          "d",
          "M9 6h7.459a3 3 0 0 1 2.959 2.507l.577 3.464l.81 4.865a1 1 0 0 1 -.985 1.164h-16.82a7 7 0 0 1 7 -7h9.8",
        ),
      ]),
    ],
  )
}

/// `ironing-1`
pub fn ironing_1(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([
        attribute.attribute(
          "d",
          "M9 6h7.459a3 3 0 0 1 2.959 2.507l.577 3.464l.81 4.865a1 1 0 0 1 -.985 1.164h-16.82a7 7 0 0 1 7 -7h9.8",
        ),
      ]),
      svg.path([attribute.attribute("d", "M12 15h.01")]),
    ],
  )
}

/// `ironing-2`
pub fn ironing_2(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([attribute.attribute("d", "M10 15h.01")]),
      svg.path([
        attribute.attribute(
          "d",
          "M9 6h7.459a3 3 0 0 1 2.959 2.507l.577 3.464l.81 4.865a1 1 0 0 1 -.985 1.164h-16.82a7 7 0 0 1 7 -7h9.8",
        ),
      ]),
      svg.path([attribute.attribute("d", "M14 15h.01")]),
    ],
  )
}

/// `ironing-3`
pub fn ironing_3(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([attribute.attribute("d", "M12 15h.01")]),
      svg.path([
        attribute.attribute(
          "d",
          "M9 6h7.459a3 3 0 0 1 2.959 2.507l.577 3.464l.81 4.865a1 1 0 0 1 -.985 1.164h-16.82a7 7 0 0 1 7 -7h9.8",
        ),
      ]),
      svg.path([attribute.attribute("d", "M9 15h.01")]),
      svg.path([attribute.attribute("d", "M15 15h.01")]),
    ],
  )
}

/// `ironing-off`
pub fn ironing_off(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([
        attribute.attribute(
          "d",
          "M10 6h6.459a3 3 0 0 1 2.959 2.507l.577 3.464l.804 4.821l.007 .044m-2.806 1.164h-15a7 7 0 0 1 7 -7h1m4 0h4.8",
        ),
      ]),
      svg.path([attribute.attribute("d", "M3 3l18 18")]),
    ],
  )
}

/// `ironing-steam`
pub fn ironing_steam(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([attribute.attribute("d", "M12 19v2")]),
      svg.path([
        attribute.attribute(
          "d",
          "M9 4h7.459a3 3 0 0 1 2.959 2.507l.577 3.464l.81 4.865a1 1 0 0 1 -.985 1.164h-16.82a7 7 0 0 1 7 -7h9.8",
        ),
      ]),
      svg.path([attribute.attribute("d", "M8 19l-1 2")]),
      svg.path([attribute.attribute("d", "M16 19l1 2")]),
    ],
  )
}

/// `ironing-steam-off`
pub fn ironing_steam_off(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([
        attribute.attribute(
          "d",
          "M9 4h7.459a3 3 0 0 1 2.959 2.507l.577 3.464l.81 4.865a1 1 0 0 1 -.821 1.15",
        ),
      ]),
      svg.path([attribute.attribute("d", "M16 16h-13a7 7 0 0 1 6.056 -6.937")]),
      svg.path([attribute.attribute("d", "M13 9h6.8")]),
      svg.path([attribute.attribute("d", "M12 19v2")]),
      svg.path([attribute.attribute("d", "M8 19l-1 2")]),
      svg.path([attribute.attribute("d", "M16 19l1 2")]),
      svg.path([attribute.attribute("d", "M3 3l18 18")]),
    ],
  )
}

/// `irregular-polyhedron`
pub fn irregular_polyhedron(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([
        attribute.attribute(
          "d",
          "M6 12l-1.752 6.13a1 1 0 0 0 .592 1.205l6.282 2.503a2.46 2.46 0 0 0 1.756 0l6.282 -2.503a1 1 0 0 0 .592 -1.204l-1.752 -6.131l1.752 -6.13a1 1 0 0 0 -.592 -1.205l-6.282 -2.503a2.46 2.46 0 0 0 -1.756 0l-6.282 2.503a1 1 0 0 0 -.592 1.204l1.752 6.131",
        ),
      ]),
      svg.path([
        attribute.attribute(
          "d",
          "M4.5 5.5l6.622 2.33a2.35 2.35 0 0 0 1.756 0l6.622 -2.33",
        ),
      ]),
      svg.path([
        attribute.attribute(
          "d",
          "M6 12l5.21 1.862a2.34 2.34 0 0 0 1.58 0l5.21 -1.862",
        ),
      ]),
      svg.path([attribute.attribute("d", "M12 22v-14")]),
    ],
  )
}

/// `irregular-polyhedron-off`
pub fn irregular_polyhedron_off(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([
        attribute.attribute(
          "d",
          "M4.706 4.73a1 1 0 0 0 -.458 1.14l1.752 6.13l-1.752 6.13a1 1 0 0 0 .592 1.205l6.282 2.503a2.46 2.46 0 0 0 1.756 0l6.282 -2.503c.04 -.016 .079 -.035 .116 -.055m-.474 -4.474l-.802 -2.806l1.752 -6.13a1 1 0 0 0 -.592 -1.205l-6.282 -2.503a2.46 2.46 0 0 0 -1.756 0l-3.544 1.412",
        ),
      ]),
      svg.path([
        attribute.attribute(
          "d",
          "M4.5 5.5c.661 .214 1.161 .38 1.5 .5m6 2c.29 -.003 .603 -.06 .878 -.17l6.622 -2.33",
        ),
      ]),
      svg.path([
        attribute.attribute(
          "d",
          "M6 12l5.21 1.862a2.34 2.34 0 0 0 1.58 0l.742 -.265m2.956 -1.057c.312 -.11 .816 -.291 1.512 -.54",
        ),
      ]),
      svg.path([attribute.attribute("d", "M12 22v-10")]),
      svg.path([attribute.attribute("d", "M3 3l18 18")]),
    ],
  )
}

/// `irregular-polyhedron-plus`
pub fn irregular_polyhedron_plus(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([
        attribute.attribute(
          "d",
          "M18 12l1.752 -6.13a1 1 0 0 0 -.592 -1.205l-6.282 -2.503a2.46 2.46 0 0 0 -1.756 0l-6.282 2.503a1 1 0 0 0 -.592 1.204l1.752 6.131l-1.752 6.13a1 1 0 0 0 .592 1.205l6.282 2.503a2.46 2.46 0 0 0 1.756 0l.221 -.088",
        ),
      ]),
      svg.path([
        attribute.attribute(
          "d",
          "M4.5 5.5l6.622 2.33a2.35 2.35 0 0 0 1.756 0l6.622 -2.33",
        ),
      ]),
      svg.path([
        attribute.attribute(
          "d",
          "M6 12l5.21 1.862a2.34 2.34 0 0 0 1.58 0l5.21 -1.862",
        ),
      ]),
      svg.path([attribute.attribute("d", "M12 22v-14")]),
      svg.path([attribute.attribute("d", "M16 19h6")]),
      svg.path([attribute.attribute("d", "M19 16v6")]),
    ],
  )
}

/// `italic`
pub fn italic(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([attribute.attribute("d", "M11 5l6 0")]),
      svg.path([attribute.attribute("d", "M7 19l6 0")]),
      svg.path([attribute.attribute("d", "M14 5l-4 14")]),
    ],
  )
}
