//// tabler · outline · shard "n". GENERATED by gg_icon_gen — do not hand-edit.

import gg_icon/icon
import gg_icons_tabler/internal
import lustre/attribute.{type Attribute}
import lustre/element.{type Element}
import lustre/element/svg

/// `navigation`
pub fn navigation(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([
        attribute.attribute(
          "d",
          "M12 18.5l7.265 2.463c.196 .077 .42 .032 .57 -.116a.548 .548 0 0 0 .134 -.572l-7.969 -17.275l-7.97 17.275c-.07 .2 -.017 .424 .135 .572c.15 .148 .374 .193 .57 .116l7.265 -2.463",
        ),
      ]),
    ],
  )
}

/// `navigation-bolt`
pub fn navigation_bolt(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([
        attribute.attribute(
          "d",
          "M16.559 12.882l-4.559 -9.882l-7.97 17.275c-.07 .2 -.017 .424 .135 .572c.15 .148 .374 .193 .57 .116l7.265 -2.463l1.036 .351",
        ),
      ]),
      svg.path([attribute.attribute("d", "M19 16l-2 3h4l-2 3")]),
    ],
  )
}

/// `navigation-cancel`
pub fn navigation_cancel(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([
        attribute.attribute(
          "d",
          "M16.371 12.476l-4.371 -9.476l-7.97 17.275c-.07 .2 -.017 .424 .135 .572c.15 .148 .374 .193 .57 .116l7.265 -2.463",
        ),
      ]),
      svg.path([attribute.attribute("d", "M16 19a3 3 0 1 0 6 0a3 3 0 1 0 -6 0")]),
      svg.path([attribute.attribute("d", "M17 21l4 -4")]),
    ],
  )
}

/// `navigation-check`
pub fn navigation_check(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([
        attribute.attribute(
          "d",
          "M17.487 14.894l-5.487 -11.894l-7.97 17.275c-.07 .2 -.017 .424 .135 .572c.15 .148 .374 .193 .57 .116l6.275 -2.127",
        ),
      ]),
      svg.path([attribute.attribute("d", "M15 19l2 2l4 -4")]),
    ],
  )
}

/// `navigation-code`
pub fn navigation_code(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([
        attribute.attribute(
          "d",
          "M16.653 13.086l-4.653 -10.086l-7.97 17.275c-.07 .2 -.017 .424 .135 .572c.15 .148 .374 .193 .57 .116l6.246 -2.117",
        ),
      ]),
      svg.path([attribute.attribute("d", "M20 21l2 -2l-2 -2")]),
      svg.path([attribute.attribute("d", "M17 17l-2 2l2 2")]),
    ],
  )
}

/// `navigation-cog`
pub fn navigation_cog(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([
        attribute.attribute(
          "d",
          "M16.387 12.51l-4.387 -9.51l-7.97 17.275c-.07 .2 -.017 .424 .135 .572c.15 .148 .374 .193 .57 .116l7.265 -2.463",
        ),
      ]),
      svg.path([
        attribute.attribute("d", "M17.001 19a2 2 0 1 0 4 0a2 2 0 1 0 -4 0"),
      ]),
      svg.path([attribute.attribute("d", "M19.001 15.5v1.5")]),
      svg.path([attribute.attribute("d", "M19.001 21v1.5")]),
      svg.path([attribute.attribute("d", "M22.032 17.25l-1.299 .75")]),
      svg.path([attribute.attribute("d", "M17.27 20l-1.3 .75")]),
      svg.path([attribute.attribute("d", "M15.97 17.25l1.3 .75")]),
      svg.path([attribute.attribute("d", "M20.733 20l1.3 .75")]),
    ],
  )
}

/// `navigation-discount`
pub fn navigation_discount(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([
        attribute.attribute(
          "d",
          "M16.43 12.603l-4.43 -9.603l-7.97 17.275c-.07 .2 -.017 .424 .135 .572c.15 .148 .374 .193 .57 .116l7.265 -2.463l1.272 .431",
        ),
      ]),
      svg.path([attribute.attribute("d", "M16 21l5 -5")]),
      svg.path([attribute.attribute("d", "M21 21v.01")]),
      svg.path([attribute.attribute("d", "M16 16v.01")]),
    ],
  )
}

/// `navigation-dollar`
pub fn navigation_dollar(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([
        attribute.attribute(
          "d",
          "M15.945 11.551l-3.945 -8.551l-7.97 17.275c-.07 .2 -.017 .424 .135 .572c.15 .148 .374 .193 .57 .116l7.265 -2.463l1.594 .54",
        ),
      ]),
      svg.path([
        attribute.attribute(
          "d",
          "M21 15h-2.5a1.5 1.5 0 0 0 0 3h1a1.5 1.5 0 0 1 0 3h-2.5",
        ),
      ]),
      svg.path([attribute.attribute("d", "M19 21v1m0 -8v1")]),
    ],
  )
}

/// `navigation-down`
pub fn navigation_down(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([
        attribute.attribute(
          "d",
          "M16.528 12.815l-4.528 -9.815l-7.97 17.275c-.07 .2 -.017 .424 .135 .572c.15 .148 .374 .193 .57 .116l7.265 -2.463",
        ),
      ]),
      svg.path([attribute.attribute("d", "M19 16v6")]),
      svg.path([attribute.attribute("d", "M22 19l-3 3l-3 -3")]),
    ],
  )
}

/// `navigation-east`
pub fn navigation_east(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([attribute.attribute("d", "M14 3h-4v6h4")]),
      svg.path([attribute.attribute("d", "M10 6h2.5")]),
      svg.path([attribute.attribute("d", "M16 21l-4 -8l-4 8l4 -2l4 2")]),
    ],
  )
}

/// `navigation-exclamation`
pub fn navigation_exclamation(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([
        attribute.attribute(
          "d",
          "M16.535 12.832l-4.535 -9.832l-7.97 17.275c-.07 .2 -.017 .424 .135 .572c.15 .148 .374 .193 .57 .116l7.265 -2.463c1.38 .468 2.416 .82 3.107 1.053",
        ),
      ]),
      svg.path([attribute.attribute("d", "M19 16v3")]),
      svg.path([attribute.attribute("d", "M19 22v.01")]),
    ],
  )
}

/// `navigation-heart`
pub fn navigation_heart(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([
        attribute.attribute(
          "d",
          "M15.721 11.067l-3.721 -8.067l-7.97 17.275c-.07 .2 -.017 .424 .135 .572c.15 .148 .374 .193 .57 .116l5.614 -1.903",
        ),
      ]),
      svg.path([
        attribute.attribute(
          "d",
          "M18 22l3.35 -3.284a2.143 2.143 0 0 0 .005 -3.071a2.242 2.242 0 0 0 -3.129 -.006l-.224 .22l-.223 -.22a2.242 2.242 0 0 0 -3.128 -.006a2.143 2.143 0 0 0 -.006 3.071l3.355 3.296",
        ),
      ]),
    ],
  )
}

/// `navigation-minus`
pub fn navigation_minus(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([
        attribute.attribute(
          "d",
          "M17.5 15c-1.232 -2.67 -3.065 -6.67 -5.5 -12l-7.97 17.275c-.07 .2 -.017 .424 .135 .572c.15 .148 .374 .193 .57 .116l7.265 -2.463",
        ),
      ]),
      svg.path([attribute.attribute("d", "M16 19h6")]),
    ],
  )
}

/// `navigation-north`
pub fn navigation_north(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([attribute.attribute("d", "M16 21l-4 -8l-4 8l4 -2l4 2")]),
      svg.path([attribute.attribute("d", "M10 9v-6l4 6v-6")]),
    ],
  )
}

/// `navigation-off`
pub fn navigation_off(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([
        attribute.attribute(
          "d",
          "M16.28 12.28c-.95 -2.064 -2.377 -5.157 -4.28 -9.28c-.7 1.515 -1.223 2.652 -1.573 3.41m-1.27 2.75c-.882 1.913 -2.59 5.618 -5.127 11.115c-.07 .2 -.017 .424 .135 .572c.15 .148 .374 .193 .57 .116l7.265 -2.463l7.265 2.463c.196 .077 .42 .032 .57 -.116a.548 .548 0 0 0 .134 -.572l-.26 -.563",
        ),
      ]),
      svg.path([attribute.attribute("d", "M3 3l18 18")]),
    ],
  )
}

/// `navigation-pause`
pub fn navigation_pause(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([
        attribute.attribute(
          "d",
          "M16.666 13.114l-4.666 -10.114l-7.97 17.275c-.07 .2 -.017 .424 .135 .572c.15 .148 .374 .193 .57 .116l7.265 -2.463l1.056 .358",
        ),
      ]),
      svg.path([attribute.attribute("d", "M17 17v5")]),
      svg.path([attribute.attribute("d", "M21 17v5")]),
    ],
  )
}

/// `navigation-pin`
pub fn navigation_pin(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([
        attribute.attribute(
          "d",
          "M16.002 11.676l-4.002 -8.676l-7.97 17.275c-.07 .2 -.017 .424 .135 .572c.15 .148 .374 .193 .57 .116l7.265 -2.463",
        ),
      ]),
      svg.path([
        attribute.attribute(
          "d",
          "M21.121 20.121a3 3 0 1 0 -4.242 0c.418 .419 1.125 1.045 2.121 1.879c1.051 -.89 1.759 -1.516 2.121 -1.879",
        ),
      ]),
      svg.path([attribute.attribute("d", "M19 18v.01")]),
    ],
  )
}

/// `navigation-plus`
pub fn navigation_plus(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([
        attribute.attribute(
          "d",
          "M16.573 12.914l-4.573 -9.914l-7.97 17.275c-.07 .2 -.017 .424 .135 .572c.15 .148 .374 .193 .57 .116l7.265 -2.463",
        ),
      ]),
      svg.path([attribute.attribute("d", "M16 19h6")]),
      svg.path([attribute.attribute("d", "M19 16v6")]),
    ],
  )
}

/// `navigation-question`
pub fn navigation_question(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([
        attribute.attribute(
          "d",
          "M16.081 11.847l-4.081 -8.847l-7.97 17.275c-.07 .2 -.017 .424 .135 .572c.15 .148 .374 .193 .57 .116l7.265 -2.463c1.35 .458 2.362 .8 3.037 1.03",
        ),
      ]),
      svg.path([attribute.attribute("d", "M19 22v.01")]),
      svg.path([
        attribute.attribute(
          "d",
          "M19 19a2.003 2.003 0 0 0 .914 -3.782a1.98 1.98 0 0 0 -2.414 .483",
        ),
      ]),
    ],
  )
}

/// `navigation-search`
pub fn navigation_search(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([
        attribute.attribute(
          "d",
          "M15.876 11.403l-3.876 -8.403l-7.97 17.275c-.07 .2 -.017 .424 .135 .572c.15 .148 .374 .193 .57 .116l6.29 -2.132",
        ),
      ]),
      svg.path([attribute.attribute("d", "M15 18a3 3 0 1 0 6 0a3 3 0 1 0 -6 0")]),
      svg.path([attribute.attribute("d", "M20.2 20.2l1.8 1.8")]),
    ],
  )
}

/// `navigation-share`
pub fn navigation_share(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([
        attribute.attribute(
          "d",
          "M16.633 13.043l-4.633 -10.043l-7.97 17.275c-.07 .2 -.017 .424 .135 .572c.15 .148 .374 .193 .57 .116l7.265 -2.463l.955 .324",
        ),
      ]),
      svg.path([attribute.attribute("d", "M16 22l5 -5")]),
      svg.path([attribute.attribute("d", "M21 21.5v-4.5h-4.5")]),
    ],
  )
}

/// `navigation-south`
pub fn navigation_south(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([
        attribute.attribute(
          "d",
          "M10 8.25c0 .414 .336 .75 .75 .75h2.25a1 1 0 0 0 1 -1v-1a1 1 0 0 0 -1 -1h-2a1 1 0 0 1 -1 -1v-1a1 1 0 0 1 1 -1h2.25a.75 .75 0 0 1 .75 .75",
        ),
      ]),
      svg.path([attribute.attribute("d", "M16 21l-4 -8l-4 8l4 -2l4 2")]),
    ],
  )
}

/// `navigation-star`
pub fn navigation_star(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([
        attribute.attribute(
          "d",
          "M15.574 10.747l-3.574 -7.747l-7.97 17.275c-.07 .2 -.017 .424 .135 .572c.15 .148 .374 .193 .57 .116l5.454 -1.85",
        ),
      ]),
      svg.path([
        attribute.attribute(
          "d",
          "M17.8 20.817l-2.172 1.138a.392 .392 0 0 1 -.568 -.41l.415 -2.411l-1.757 -1.707a.389 .389 0 0 1 .217 -.665l2.428 -.352l1.086 -2.193a.392 .392 0 0 1 .702 0l1.086 2.193l2.428 .352a.39 .39 0 0 1 .217 .665l-1.757 1.707l.414 2.41a.39 .39 0 0 1 -.567 .411l-2.172 -1.138",
        ),
      ]),
    ],
  )
}

/// `navigation-top`
pub fn navigation_top(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([
        attribute.attribute(
          "d",
          "M16.54 19.977a.34 .34 0 0 0 .357 -.07a.33 .33 0 0 0 .084 -.35l-4.981 -10.557l-4.982 10.557a.33 .33 0 0 0 .084 .35a.34 .34 0 0 0 .357 .07l4.541 -1.477l4.54 1.477",
        ),
      ]),
      svg.path([attribute.attribute("d", "M12 3v2")]),
    ],
  )
}

/// `navigation-up`
pub fn navigation_up(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([
        attribute.attribute(
          "d",
          "M16.54 12.843l-4.54 -9.843l-7.97 17.275c-.07 .2 -.017 .424 .135 .572c.15 .148 .374 .193 .57 .116l7.265 -2.463",
        ),
      ]),
      svg.path([attribute.attribute("d", "M19 22v-6")]),
      svg.path([attribute.attribute("d", "M22 19l-3 -3l-3 3")]),
    ],
  )
}

/// `navigation-west`
pub fn navigation_west(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([attribute.attribute("d", "M9 3l1 6l2 -3.75l2 3.75l1 -6")]),
      svg.path([attribute.attribute("d", "M16 21l-4 -8l-4 8l4 -2l4 2")]),
    ],
  )
}

/// `navigation-x`
pub fn navigation_x(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([
        attribute.attribute(
          "d",
          "M16.622 13.02l-4.622 -10.02l-7.97 17.275c-.07 .2 -.017 .424 .135 .572c.15 .148 .374 .193 .57 .116l7.265 -2.463l1.563 .53",
        ),
      ]),
      svg.path([attribute.attribute("d", "M22 22l-5 -5")]),
      svg.path([attribute.attribute("d", "M17 22l5 -5")]),
    ],
  )
}

/// `needle`
pub fn needle(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([
        attribute.attribute(
          "d",
          "M3 21c-.667 -.667 3.262 -6.236 11.785 -16.709a3.5 3.5 0 1 1 5.078 4.791c-10.575 8.612 -16.196 12.585 -16.863 11.918",
        ),
      ]),
      svg.path([attribute.attribute("d", "M17.5 6.5l-1 1")]),
    ],
  )
}

/// `needle-thread`
pub fn needle_thread(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([
        attribute.attribute(
          "d",
          "M3 21c-.667 -.667 3.262 -6.236 11.785 -16.709a3.5 3.5 0 1 1 5.078 4.791c-10.575 8.612 -16.196 12.585 -16.863 11.918",
        ),
      ]),
      svg.path([attribute.attribute("d", "M17.5 6.5l-1 1")]),
      svg.path([
        attribute.attribute(
          "d",
          "M17 7c-2.333 -2.667 -3.5 -4 -5 -4s-2 1 -2 2c0 4 8.161 8.406 6 11c-1.056 1.268 -3.363 1.285 -5.75 .808",
        ),
      ]),
      svg.path([
        attribute.attribute(
          "d",
          "M5.739 15.425c-1.393 -.565 -3.739 -1.925 -3.739 -3.425",
        ),
      ]),
      svg.path([attribute.attribute("d", "M19.5 9.5l1.5 1.5")]),
    ],
  )
}

/// `network`
pub fn network(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([attribute.attribute("d", "M6 9a6 6 0 1 0 12 0a6 6 0 0 0 -12 0")]),
      svg.path([
        attribute.attribute(
          "d",
          "M12 3c1.333 .333 2 2.333 2 6s-.667 5.667 -2 6",
        ),
      ]),
      svg.path([
        attribute.attribute(
          "d",
          "M12 3c-1.333 .333 -2 2.333 -2 6s.667 5.667 2 6",
        ),
      ]),
      svg.path([attribute.attribute("d", "M6 9h12")]),
      svg.path([attribute.attribute("d", "M3 20h7")]),
      svg.path([attribute.attribute("d", "M14 20h7")]),
      svg.path([attribute.attribute("d", "M10 20a2 2 0 1 0 4 0a2 2 0 0 0 -4 0")]),
      svg.path([attribute.attribute("d", "M12 15v3")]),
    ],
  )
}

/// `network-off`
pub fn network_off(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([
        attribute.attribute(
          "d",
          "M6.528 6.536a6 6 0 0 0 7.942 7.933m2.247 -1.76a6 6 0 0 0 -8.427 -8.425",
        ),
      ]),
      svg.path([
        attribute.attribute(
          "d",
          "M12 3c1.333 .333 2 2.333 2 6c0 .337 -.006 .66 -.017 .968m-.55 3.473c-.333 .884 -.81 1.403 -1.433 1.559",
        ),
      ]),
      svg.path([
        attribute.attribute(
          "d",
          "M12 3c-.936 .234 -1.544 1.29 -1.822 3.167m-.16 3.838c.116 3.029 .776 4.695 1.982 4.995",
        ),
      ]),
      svg.path([attribute.attribute("d", "M6 9h3m4 0h5")]),
      svg.path([attribute.attribute("d", "M3 20h7")]),
      svg.path([attribute.attribute("d", "M14 20h7")]),
      svg.path([attribute.attribute("d", "M10 20a2 2 0 1 0 4 0a2 2 0 0 0 -4 0")]),
      svg.path([attribute.attribute("d", "M12 15v3")]),
      svg.path([attribute.attribute("d", "M3 3l18 18")]),
    ],
  )
}

/// `new-section`
pub fn new_section(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([attribute.attribute("d", "M9 12l6 0")]),
      svg.path([attribute.attribute("d", "M12 9l0 6")]),
      svg.path([
        attribute.attribute(
          "d",
          "M4 6v-1a1 1 0 0 1 1 -1h1m5 0h2m5 0h1a1 1 0 0 1 1 1v1m0 5v2m0 5v1a1 1 0 0 1 -1 1h-1m-5 0h-2m-5 0h-1a1 1 0 0 1 -1 -1v-1m0 -5v-2m0 -5",
        ),
      ]),
    ],
  )
}

/// `news`
pub fn news(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([
        attribute.attribute(
          "d",
          "M16 6h3a1 1 0 0 1 1 1v11a2 2 0 0 1 -4 0v-13a1 1 0 0 0 -1 -1h-10a1 1 0 0 0 -1 1v12a3 3 0 0 0 3 3h11",
        ),
      ]),
      svg.path([attribute.attribute("d", "M8 8l4 0")]),
      svg.path([attribute.attribute("d", "M8 12l4 0")]),
      svg.path([attribute.attribute("d", "M8 16l4 0")]),
    ],
  )
}

/// `news-off`
pub fn news_off(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([
        attribute.attribute(
          "d",
          "M16 6h3a1 1 0 0 1 1 1v9m-.606 3.435a2 2 0 0 1 -3.394 -1.435v-2m0 -4v-7a1 1 0 0 0 -1 -1h-7m-3.735 .321a1 1 0 0 0 -.265 .679v12a3 3 0 0 0 3 3h11",
        ),
      ]),
      svg.path([attribute.attribute("d", "M8 12h4")]),
      svg.path([attribute.attribute("d", "M8 16h4")]),
      svg.path([attribute.attribute("d", "M3 3l18 18")]),
    ],
  )
}

/// `nfc`
pub fn nfc(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([attribute.attribute("d", "M11 20a3 3 0 0 1 -3 -3v-11l5 5")]),
      svg.path([attribute.attribute("d", "M13 4a3 3 0 0 1 3 3v11l-5 -5")]),
      svg.path([
        attribute.attribute(
          "d",
          "M4 7a3 3 0 0 1 3 -3h10a3 3 0 0 1 3 3v10a3 3 0 0 1 -3 3h-10a3 3 0 0 1 -3 -3l0 -10",
        ),
      ]),
    ],
  )
}

/// `nfc-off`
pub fn nfc_off(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([attribute.attribute("d", "M11 20a3 3 0 0 1 -3 -3v-9")]),
      svg.path([attribute.attribute("d", "M13 4a3 3 0 0 1 3 3v5m0 4v2l-5 -5")]),
      svg.path([
        attribute.attribute(
          "d",
          "M8 4h9a3 3 0 0 1 3 3v9m-.873 3.116a2.99 2.99 0 0 1 -2.127 .884h-10a3 3 0 0 1 -3 -3v-10c0 -.83 .337 -1.582 .882 -2.125",
        ),
      ]),
      svg.path([attribute.attribute("d", "M3 3l18 18")]),
    ],
  )
}

/// `no-copyright`
pub fn no_copyright(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([
        attribute.attribute("d", "M3 12a9 9 0 1 0 18 0a9 9 0 1 0 -18 0"),
      ]),
      svg.path([
        attribute.attribute(
          "d",
          "M14 9.75a3.016 3.016 0 0 0 -4.163 .173a2.993 2.993 0 0 0 0 4.154a3.016 3.016 0 0 0 4.163 .173",
        ),
      ]),
      svg.path([attribute.attribute("d", "M6 6l1.5 1.5")]),
      svg.path([attribute.attribute("d", "M16.5 16.5l1.5 1.5")]),
    ],
  )
}

/// `no-creative-commons`
pub fn no_creative_commons(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([
        attribute.attribute("d", "M3 12a9 9 0 1 0 18 0a9 9 0 1 0 -18 0"),
      ]),
      svg.path([
        attribute.attribute(
          "d",
          "M10.5 10.5c-.847 -.71 -2.132 -.658 -2.914 .116a1.928 1.928 0 0 0 0 2.768c.782 .774 2.067 .825 2.914 .116",
        ),
      ]),
      svg.path([
        attribute.attribute(
          "d",
          "M16.5 10.5c-.847 -.71 -2.132 -.658 -2.914 .116a1.928 1.928 0 0 0 0 2.768c.782 .774 2.067 .825 2.914 .116",
        ),
      ]),
      svg.path([attribute.attribute("d", "M6 6l1.5 1.5")]),
      svg.path([attribute.attribute("d", "M16.5 16.5l1.5 1.5")]),
    ],
  )
}

/// `no-derivatives`
pub fn no_derivatives(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([
        attribute.attribute("d", "M3 12a9 9 0 1 0 18 0a9 9 0 1 0 -18 0"),
      ]),
      svg.path([attribute.attribute("d", "M9 10h6")]),
      svg.path([attribute.attribute("d", "M9 14h6")]),
    ],
  )
}

/// `noise-reduction`
pub fn noise_reduction(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([
        attribute.attribute("d", "M21 12a9 9 0 1 1 -18 0a9 9 0 0 1 18 0"),
      ]),
      svg.path([attribute.attribute("d", "M10.01 18h-.01")]),
      svg.path([attribute.attribute("d", "M14.01 14h-.01")]),
      svg.path([attribute.attribute("d", "M16.01 12h-.01")]),
      svg.path([attribute.attribute("d", "M18.01 10h-.01")]),
      svg.path([attribute.attribute("d", "M16.01 16h-.01")]),
      svg.path([attribute.attribute("d", "M14.01 18h-.01")]),
      svg.path([attribute.attribute("d", "M18.01 14h-.01")]),
      svg.path([attribute.attribute("d", "M12.01 16h-.01")]),
    ],
  )
}

/// `north-star`
pub fn north_star(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([attribute.attribute("d", "M3 12h18")]),
      svg.path([attribute.attribute("d", "M12 21v-18")]),
      svg.path([attribute.attribute("d", "M7.5 7.5l9 9")]),
      svg.path([attribute.attribute("d", "M7.5 16.5l9 -9")]),
    ],
  )
}

/// `notdef`
pub fn notdef(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([attribute.attribute("d", "M18.49 3.666l-12.976 16.673")]),
      svg.path([attribute.attribute("d", "M5.51 3.666l12.976 16.673")]),
      svg.path([
        attribute.attribute(
          "d",
          "M5 5a2 2 0 0 1 2 -2h10a2 2 0 0 1 2 2v14a2 2 0 0 1 -2 2h-10a2 2 0 0 1 -2 -2v-14",
        ),
      ]),
    ],
  )
}

/// `note`
pub fn note(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([attribute.attribute("d", "M13 20l7 -7")]),
      svg.path([
        attribute.attribute(
          "d",
          "M13 20v-6a1 1 0 0 1 1 -1h6v-7a2 2 0 0 0 -2 -2h-12a2 2 0 0 0 -2 2v12a2 2 0 0 0 2 2h7",
        ),
      ]),
    ],
  )
}

/// `note-off`
pub fn note_off(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([
        attribute.attribute("d", "M13 20l3.505 -3.505m2 -2l1.501 -1.501"),
      ]),
      svg.path([
        attribute.attribute(
          "d",
          "M17 13h3v-7a2 2 0 0 0 -2 -2h-10m-3.427 .6c-.355 .36 -.573 .853 -.573 1.4v12a2 2 0 0 0 2 2h7v-6c0 -.272 .109 -.519 .285 -.699",
        ),
      ]),
      svg.path([attribute.attribute("d", "M3 3l18 18")]),
    ],
  )
}

/// `notebook`
pub fn notebook(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([
        attribute.attribute(
          "d",
          "M6 4h11a2 2 0 0 1 2 2v12a2 2 0 0 1 -2 2h-11a1 1 0 0 1 -1 -1v-14a1 1 0 0 1 1 -1m3 0v18",
        ),
      ]),
      svg.path([attribute.attribute("d", "M13 8l2 0")]),
      svg.path([attribute.attribute("d", "M13 12l2 0")]),
    ],
  )
}

/// `notebook-off`
pub fn notebook_off(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([
        attribute.attribute(
          "d",
          "M8 4h9a2 2 0 0 1 2 2v9m-.179 3.828a2 2 0 0 1 -1.821 1.172h-11a1 1 0 0 1 -1 -1v-14m4 -1v1m0 4v13",
        ),
      ]),
      svg.path([attribute.attribute("d", "M13 8h2")]),
      svg.path([attribute.attribute("d", "M3 3l18 18")]),
    ],
  )
}

/// `notes`
pub fn notes(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([
        attribute.attribute(
          "d",
          "M5 5a2 2 0 0 1 2 -2h10a2 2 0 0 1 2 2v14a2 2 0 0 1 -2 2h-10a2 2 0 0 1 -2 -2l0 -14",
        ),
      ]),
      svg.path([attribute.attribute("d", "M9 7l6 0")]),
      svg.path([attribute.attribute("d", "M9 11l6 0")]),
      svg.path([attribute.attribute("d", "M9 15l4 0")]),
    ],
  )
}

/// `notes-off`
pub fn notes_off(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([
        attribute.attribute(
          "d",
          "M7 3h10a2 2 0 0 1 2 2v10m0 4a2 2 0 0 1 -2 2h-10a2 2 0 0 1 -2 -2v-14",
        ),
      ]),
      svg.path([attribute.attribute("d", "M11 7h4")]),
      svg.path([attribute.attribute("d", "M9 11h2")]),
      svg.path([attribute.attribute("d", "M9 15h4")]),
      svg.path([attribute.attribute("d", "M3 3l18 18")]),
    ],
  )
}

/// `notification`
pub fn notification(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([
        attribute.attribute(
          "d",
          "M10 6h-3a2 2 0 0 0 -2 2v9a2 2 0 0 0 2 2h9a2 2 0 0 0 2 -2v-3",
        ),
      ]),
      svg.path([attribute.attribute("d", "M14 7a3 3 0 1 0 6 0a3 3 0 1 0 -6 0")]),
    ],
  )
}

/// `notification-off`
pub fn notification_off(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([
        attribute.attribute(
          "d",
          "M6.154 6.187a2 2 0 0 0 -1.154 1.813v9a2 2 0 0 0 2 2h9a2 2 0 0 0 1.811 -1.151",
        ),
      ]),
      svg.path([attribute.attribute("d", "M14 7a3 3 0 1 0 6 0a3 3 0 1 0 -6 0")]),
      svg.path([attribute.attribute("d", "M3 3l18 18")]),
    ],
  )
}

/// `number`
pub fn number(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([attribute.attribute("d", "M4 17v-10l7 10v-10")]),
      svg.path([attribute.attribute("d", "M15 17h5")]),
      svg.path([
        attribute.attribute("d", "M15 10a2.5 3 0 1 0 5 0a2.5 3 0 1 0 -5 0"),
      ]),
    ],
  )
}

/// `number-0`
pub fn number_0(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([attribute.attribute("d", "M16 16v-8")]),
      svg.path([
        attribute.attribute(
          "d",
          "M12 20a4 4 0 0 0 4 -4v-8a4 4 0 1 0 -8 0v8a4 4 0 0 0 4 4",
        ),
      ]),
    ],
  )
}

/// `number-0-small`
pub fn number_0_small(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([
        attribute.attribute("d", "M10 10v4a2 2 0 1 0 4 0v-4a2 2 0 1 0 -4 0"),
      ]),
    ],
  )
}

/// `number-1`
pub fn number_1(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [svg.path([attribute.attribute("d", "M13 20v-16l-5 5")])],
  )
}

/// `number-10`
pub fn number_10(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([attribute.attribute("d", "M8 20v-16l-5 5")]),
      svg.path([
        attribute.attribute(
          "d",
          "M16 20a4 4 0 0 0 4 -4v-8a4 4 0 1 0 -8 0v8a4 4 0 0 0 4 4",
        ),
      ]),
    ],
  )
}

/// `number-100-small`
pub fn number_100_small(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([attribute.attribute("d", "M4 8h1v8")]),
      svg.path([
        attribute.attribute("d", "M9 10v4a2 2 0 1 0 4 0v-4a2 2 0 1 0 -4 0"),
      ]),
      svg.path([
        attribute.attribute("d", "M16 10v4a2 2 0 1 0 4 0v-4a2 2 0 1 0 -4 0"),
      ]),
    ],
  )
}

/// `number-10-small`
pub fn number_10_small(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([attribute.attribute("d", "M8 8h1v8")]),
      svg.path([
        attribute.attribute("d", "M14 10v4a2 2 0 1 0 4 0v-4a2 2 0 1 0 -4 0"),
      ]),
    ],
  )
}

/// `number-11`
pub fn number_11(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([attribute.attribute("d", "M8 20v-16l-5 5")]),
      svg.path([attribute.attribute("d", "M18 20v-16l-5 5")]),
    ],
  )
}

/// `number-11-small`
pub fn number_11_small(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([attribute.attribute("d", "M8 8h1v8")]),
      svg.path([attribute.attribute("d", "M14 8h1v8")]),
    ],
  )
}

/// `number-123`
pub fn number_123(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([attribute.attribute("d", "M3 10l2 -2v8")]),
      svg.path([
        attribute.attribute(
          "d",
          "M9 8h3a1 1 0 0 1 1 1v2a1 1 0 0 1 -1 1h-2a1 1 0 0 0 -1 1v2a1 1 0 0 0 1 1h3",
        ),
      ]),
      svg.path([
        attribute.attribute(
          "d",
          "M17 8h2.5a1.5 1.5 0 0 1 1.5 1.5v1a1.5 1.5 0 0 1 -1.5 1.5h-1.5h1.5a1.5 1.5 0 0 1 1.5 1.5v1a1.5 1.5 0 0 1 -1.5 1.5h-2.5",
        ),
      ]),
    ],
  )
}

/// `number-12-small`
pub fn number_12_small(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([attribute.attribute("d", "M8 8h1v8")]),
      svg.path([
        attribute.attribute(
          "d",
          "M13 8h3a1 1 0 0 1 1 1v2a1 1 0 0 1 -1 1h-2a1 1 0 0 0 -1 1v2a1 1 0 0 0 1 1h3",
        ),
      ]),
    ],
  )
}

/// `number-13-small`
pub fn number_13_small(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([attribute.attribute("d", "M8 8h1v8")]),
      svg.path([
        attribute.attribute(
          "d",
          "M13 8h2.5a1.5 1.5 0 0 1 1.5 1.5v1a1.5 1.5 0 0 1 -1.5 1.5h-1.5h1.5a1.5 1.5 0 0 1 1.5 1.5v1a1.5 1.5 0 0 1 -1.5 1.5h-2.5",
        ),
      ]),
    ],
  )
}

/// `number-14-small`
pub fn number_14_small(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([attribute.attribute("d", "M8 8h1v8")]),
      svg.path([attribute.attribute("d", "M13 8v3a1 1 0 0 0 1 1h3")]),
      svg.path([attribute.attribute("d", "M17 8v8")]),
    ],
  )
}

/// `number-15-small`
pub fn number_15_small(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([attribute.attribute("d", "M8 8h1v8")]),
      svg.path([
        attribute.attribute(
          "d",
          "M13 15a1 1 0 0 0 1 1h2a1 1 0 0 0 1 -1v-2a1 1 0 0 0 -1 -1h-3v-4h4",
        ),
      ]),
    ],
  )
}

/// `number-16-small`
pub fn number_16_small(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([attribute.attribute("d", "M8 8h1v8")]),
      svg.path([
        attribute.attribute(
          "d",
          "M17 9a1 1 0 0 0 -1 -1h-2a1 1 0 0 0 -1 1v6a1 1 0 0 0 1 1h2a1 1 0 0 0 1 -1v-2a1 1 0 0 0 -1 -1h-3",
        ),
      ]),
    ],
  )
}

/// `number-17-small`
pub fn number_17_small(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([attribute.attribute("d", "M8 8h1v8")]),
      svg.path([attribute.attribute("d", "M13 8h4l-2 8")]),
    ],
  )
}

/// `number-18-small`
pub fn number_18_small(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([attribute.attribute("d", "M8 8h1v8")]),
      svg.path([
        attribute.attribute(
          "d",
          "M15 12h-1a1 1 0 0 1 -1 -1v-2a1 1 0 0 1 1 -1h2a1 1 0 0 1 1 1v2a1 1 0 0 1 -1 1h-2a1 1 0 0 0 -1 1v2a1 1 0 0 0 1 1h2a1 1 0 0 0 1 -1v-2a1 1 0 0 0 -1 -1",
        ),
      ]),
    ],
  )
}

/// `number-19-small`
pub fn number_19_small(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([attribute.attribute("d", "M8 8h1v8")]),
      svg.path([
        attribute.attribute(
          "d",
          "M13 15a1 1 0 0 0 1 1h2a1 1 0 0 0 1 -1v-6a1 1 0 0 0 -1 -1h-2a1 1 0 0 0 -1 1v2a1 1 0 0 0 1 1h3",
        ),
      ]),
    ],
  )
}

/// `number-1-small`
pub fn number_1_small(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [svg.path([attribute.attribute("d", "M11 8h1v8")])],
  )
}

/// `number-2`
pub fn number_2(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([
        attribute.attribute(
          "d",
          "M8 8a4 4 0 1 1 8 0c0 1.098 -.564 2.025 -1.159 2.815l-6.841 9.185h8",
        ),
      ]),
    ],
  )
}

/// `number-20-small`
pub fn number_20_small(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([
        attribute.attribute("d", "M14 10v4a2 2 0 1 0 4 0v-4a2 2 0 1 0 -4 0"),
      ]),
      svg.path([
        attribute.attribute(
          "d",
          "M6 8h3a1 1 0 0 1 1 1v2a1 1 0 0 1 -1 1h-2a1 1 0 0 0 -1 1v2a1 1 0 0 0 1 1h3",
        ),
      ]),
    ],
  )
}

/// `number-21-small`
pub fn number_21_small(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([attribute.attribute("d", "M15 8h1v8")]),
      svg.path([
        attribute.attribute(
          "d",
          "M7 8h3a1 1 0 0 1 1 1v2a1 1 0 0 1 -1 1h-2a1 1 0 0 0 -1 1v2a1 1 0 0 0 1 1h3",
        ),
      ]),
    ],
  )
}

/// `number-22-small`
pub fn number_22_small(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([
        attribute.attribute(
          "d",
          "M14 8h3a1 1 0 0 1 1 1v2a1 1 0 0 1 -1 1h-2a1 1 0 0 0 -1 1v2a1 1 0 0 0 1 1h3",
        ),
      ]),
      svg.path([
        attribute.attribute(
          "d",
          "M6 8h3a1 1 0 0 1 1 1v2a1 1 0 0 1 -1 1h-2a1 1 0 0 0 -1 1v2a1 1 0 0 0 1 1h3",
        ),
      ]),
    ],
  )
}

/// `number-23-small`
pub fn number_23_small(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([
        attribute.attribute(
          "d",
          "M14 8h2.5a1.5 1.5 0 0 1 1.5 1.5v1a1.5 1.5 0 0 1 -1.5 1.5h-1.5h1.5a1.5 1.5 0 0 1 1.5 1.5v1a1.5 1.5 0 0 1 -1.5 1.5h-2.5",
        ),
      ]),
      svg.path([
        attribute.attribute(
          "d",
          "M6 8h3a1 1 0 0 1 1 1v2a1 1 0 0 1 -1 1h-2a1 1 0 0 0 -1 1v2a1 1 0 0 0 1 1h3",
        ),
      ]),
    ],
  )
}

/// `number-24-small`
pub fn number_24_small(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([attribute.attribute("d", "M14 8v3a1 1 0 0 0 1 1h3")]),
      svg.path([attribute.attribute("d", "M18 8v8")]),
      svg.path([
        attribute.attribute(
          "d",
          "M6 8h3a1 1 0 0 1 1 1v2a1 1 0 0 1 -1 1h-2a1 1 0 0 0 -1 1v2a1 1 0 0 0 1 1h3",
        ),
      ]),
    ],
  )
}

/// `number-25-small`
pub fn number_25_small(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([
        attribute.attribute(
          "d",
          "M14 15a1 1 0 0 0 1 1h2a1 1 0 0 0 1 -1v-2a1 1 0 0 0 -1 -1h-3v-4h4",
        ),
      ]),
      svg.path([
        attribute.attribute(
          "d",
          "M6 8h3a1 1 0 0 1 1 1v2a1 1 0 0 1 -1 1h-2a1 1 0 0 0 -1 1v2a1 1 0 0 0 1 1h3",
        ),
      ]),
    ],
  )
}

/// `number-26-small`
pub fn number_26_small(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([
        attribute.attribute(
          "d",
          "M18 9a1 1 0 0 0 -1 -1h-2a1 1 0 0 0 -1 1v6a1 1 0 0 0 1 1h2a1 1 0 0 0 1 -1v-2a1 1 0 0 0 -1 -1h-3",
        ),
      ]),
      svg.path([
        attribute.attribute(
          "d",
          "M6 8h3a1 1 0 0 1 1 1v2a1 1 0 0 1 -1 1h-2a1 1 0 0 0 -1 1v2a1 1 0 0 0 1 1h3",
        ),
      ]),
    ],
  )
}

/// `number-27-small`
pub fn number_27_small(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([attribute.attribute("d", "M14 8h4l-2 8")]),
      svg.path([
        attribute.attribute(
          "d",
          "M6 8h3a1 1 0 0 1 1 1v2a1 1 0 0 1 -1 1h-2a1 1 0 0 0 -1 1v2a1 1 0 0 0 1 1h3",
        ),
      ]),
    ],
  )
}

/// `number-28-small`
pub fn number_28_small(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([
        attribute.attribute(
          "d",
          "M16 12h-1a1 1 0 0 1 -1 -1v-2a1 1 0 0 1 1 -1h2a1 1 0 0 1 1 1v2a1 1 0 0 1 -1 1h-2a1 1 0 0 0 -1 1v2a1 1 0 0 0 1 1h2a1 1 0 0 0 1 -1v-2a1 1 0 0 0 -1 -1",
        ),
      ]),
      svg.path([
        attribute.attribute(
          "d",
          "M6 8h3a1 1 0 0 1 1 1v2a1 1 0 0 1 -1 1h-2a1 1 0 0 0 -1 1v2a1 1 0 0 0 1 1h3",
        ),
      ]),
    ],
  )
}

/// `number-29-small`
pub fn number_29_small(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([
        attribute.attribute(
          "d",
          "M14 15a1 1 0 0 0 1 1h2a1 1 0 0 0 1 -1v-6a1 1 0 0 0 -1 -1h-2a1 1 0 0 0 -1 1v2a1 1 0 0 0 1 1h3",
        ),
      ]),
      svg.path([
        attribute.attribute(
          "d",
          "M6 8h3a1 1 0 0 1 1 1v2a1 1 0 0 1 -1 1h-2a1 1 0 0 0 -1 1v2a1 1 0 0 0 1 1h3",
        ),
      ]),
    ],
  )
}

/// `number-2-small`
pub fn number_2_small(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([
        attribute.attribute(
          "d",
          "M10 8h3a1 1 0 0 1 1 1v2a1 1 0 0 1 -1 1h-2a1 1 0 0 0 -1 1v2a1 1 0 0 0 1 1h3",
        ),
      ]),
    ],
  )
}

/// `number-3`
pub fn number_3(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([attribute.attribute("d", "M12 12a4 4 0 1 0 -4 -4")]),
      svg.path([attribute.attribute("d", "M8 16a4 4 0 1 0 4 -4")]),
    ],
  )
}

/// `number-30-small`
pub fn number_30_small(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([
        attribute.attribute("d", "M14 10v4a2 2 0 1 0 4 0v-4a2 2 0 1 0 -4 0"),
      ]),
      svg.path([
        attribute.attribute(
          "d",
          "M6 8h2.5a1.5 1.5 0 0 1 1.5 1.5v1a1.5 1.5 0 0 1 -1.5 1.5h-1.5h1.5a1.5 1.5 0 0 1 1.5 1.5v1a1.5 1.5 0 0 1 -1.5 1.5h-2.5",
        ),
      ]),
    ],
  )
}

/// `number-31-small`
pub fn number_31_small(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([attribute.attribute("d", "M15 8h1v8")]),
      svg.path([
        attribute.attribute(
          "d",
          "M7 8h2.5a1.5 1.5 0 0 1 1.5 1.5v1a1.5 1.5 0 0 1 -1.5 1.5h-1.5h1.5a1.5 1.5 0 0 1 1.5 1.5v1a1.5 1.5 0 0 1 -1.5 1.5h-2.5",
        ),
      ]),
    ],
  )
}

/// `number-32-small`
pub fn number_32_small(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([
        attribute.attribute(
          "d",
          "M14 8h3a1 1 0 0 1 1 1v2a1 1 0 0 1 -1 1h-2a1 1 0 0 0 -1 1v2a1 1 0 0 0 1 1h3",
        ),
      ]),
      svg.path([
        attribute.attribute(
          "d",
          "M6 8h2.5a1.5 1.5 0 0 1 1.5 1.5v1a1.5 1.5 0 0 1 -1.5 1.5h-1.5h1.5a1.5 1.5 0 0 1 1.5 1.5v1a1.5 1.5 0 0 1 -1.5 1.5h-2.5",
        ),
      ]),
    ],
  )
}

/// `number-33-small`
pub fn number_33_small(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([
        attribute.attribute(
          "d",
          "M14 8h2.5a1.5 1.5 0 0 1 1.5 1.5v1a1.5 1.5 0 0 1 -1.5 1.5h-1.5h1.5a1.5 1.5 0 0 1 1.5 1.5v1a1.5 1.5 0 0 1 -1.5 1.5h-2.5",
        ),
      ]),
      svg.path([
        attribute.attribute(
          "d",
          "M6 8h2.5a1.5 1.5 0 0 1 1.5 1.5v1a1.5 1.5 0 0 1 -1.5 1.5h-1.5h1.5a1.5 1.5 0 0 1 1.5 1.5v1a1.5 1.5 0 0 1 -1.5 1.5h-2.5",
        ),
      ]),
    ],
  )
}

/// `number-34-small`
pub fn number_34_small(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([attribute.attribute("d", "M14 8v3a1 1 0 0 0 1 1h3")]),
      svg.path([attribute.attribute("d", "M18 8v8")]),
      svg.path([
        attribute.attribute(
          "d",
          "M6 8h2.5a1.5 1.5 0 0 1 1.5 1.5v1a1.5 1.5 0 0 1 -1.5 1.5h-1.5h1.5a1.5 1.5 0 0 1 1.5 1.5v1a1.5 1.5 0 0 1 -1.5 1.5h-2.5",
        ),
      ]),
    ],
  )
}

/// `number-35-small`
pub fn number_35_small(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([
        attribute.attribute(
          "d",
          "M14 15a1 1 0 0 0 1 1h2a1 1 0 0 0 1 -1v-2a1 1 0 0 0 -1 -1h-3v-4h4",
        ),
      ]),
      svg.path([
        attribute.attribute(
          "d",
          "M6 8h2.5a1.5 1.5 0 0 1 1.5 1.5v1a1.5 1.5 0 0 1 -1.5 1.5h-1.5h1.5a1.5 1.5 0 0 1 1.5 1.5v1a1.5 1.5 0 0 1 -1.5 1.5h-2.5",
        ),
      ]),
    ],
  )
}

/// `number-36-small`
pub fn number_36_small(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([
        attribute.attribute(
          "d",
          "M18 9a1 1 0 0 0 -1 -1h-2a1 1 0 0 0 -1 1v6a1 1 0 0 0 1 1h2a1 1 0 0 0 1 -1v-2a1 1 0 0 0 -1 -1h-3",
        ),
      ]),
      svg.path([
        attribute.attribute(
          "d",
          "M6 8h2.5a1.5 1.5 0 0 1 1.5 1.5v1a1.5 1.5 0 0 1 -1.5 1.5h-1.5h1.5a1.5 1.5 0 0 1 1.5 1.5v1a1.5 1.5 0 0 1 -1.5 1.5h-2.5",
        ),
      ]),
    ],
  )
}

/// `number-37-small`
pub fn number_37_small(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([attribute.attribute("d", "M14 8h4l-2 8")]),
      svg.path([
        attribute.attribute(
          "d",
          "M6 8h2.5a1.5 1.5 0 0 1 1.5 1.5v1a1.5 1.5 0 0 1 -1.5 1.5h-1.5h1.5a1.5 1.5 0 0 1 1.5 1.5v1a1.5 1.5 0 0 1 -1.5 1.5h-2.5",
        ),
      ]),
    ],
  )
}

/// `number-38-small`
pub fn number_38_small(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([
        attribute.attribute(
          "d",
          "M16 12h-1a1 1 0 0 1 -1 -1v-2a1 1 0 0 1 1 -1h2a1 1 0 0 1 1 1v2a1 1 0 0 1 -1 1h-2a1 1 0 0 0 -1 1v2a1 1 0 0 0 1 1h2a1 1 0 0 0 1 -1v-2a1 1 0 0 0 -1 -1",
        ),
      ]),
      svg.path([
        attribute.attribute(
          "d",
          "M6 8h2.5a1.5 1.5 0 0 1 1.5 1.5v1a1.5 1.5 0 0 1 -1.5 1.5h-1.5h1.5a1.5 1.5 0 0 1 1.5 1.5v1a1.5 1.5 0 0 1 -1.5 1.5h-2.5",
        ),
      ]),
    ],
  )
}

/// `number-39-small`
pub fn number_39_small(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([
        attribute.attribute(
          "d",
          "M14 15a1 1 0 0 0 1 1h2a1 1 0 0 0 1 -1v-6a1 1 0 0 0 -1 -1h-2a1 1 0 0 0 -1 1v2a1 1 0 0 0 1 1h3",
        ),
      ]),
      svg.path([
        attribute.attribute(
          "d",
          "M6 8h2.5a1.5 1.5 0 0 1 1.5 1.5v1a1.5 1.5 0 0 1 -1.5 1.5h-1.5h1.5a1.5 1.5 0 0 1 1.5 1.5v1a1.5 1.5 0 0 1 -1.5 1.5h-2.5",
        ),
      ]),
    ],
  )
}

/// `number-3-small`
pub fn number_3_small(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([
        attribute.attribute(
          "d",
          "M10 8h2.5a1.5 1.5 0 0 1 1.5 1.5v1a1.5 1.5 0 0 1 -1.5 1.5h-1.5h1.5a1.5 1.5 0 0 1 1.5 1.5v1a1.5 1.5 0 0 1 -1.5 1.5h-2.5",
        ),
      ]),
    ],
  )
}

/// `number-4`
pub fn number_4(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [svg.path([attribute.attribute("d", "M15 20v-15l-8 11h10")])],
  )
}

/// `number-40-small`
pub fn number_40_small(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([
        attribute.attribute("d", "M14 10v4a2 2 0 1 0 4 0v-4a2 2 0 1 0 -4 0"),
      ]),
      svg.path([attribute.attribute("d", "M6 8v3a1 1 0 0 0 1 1h3")]),
      svg.path([attribute.attribute("d", "M10 8v8")]),
    ],
  )
}

/// `number-41-small`
pub fn number_41_small(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([attribute.attribute("d", "M15 8h1v8")]),
      svg.path([attribute.attribute("d", "M6 8v3a1 1 0 0 0 1 1h3")]),
      svg.path([attribute.attribute("d", "M10 8v8")]),
    ],
  )
}

/// `number-42-small`
pub fn number_42_small(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([
        attribute.attribute(
          "d",
          "M14 8h3a1 1 0 0 1 1 1v2a1 1 0 0 1 -1 1h-2a1 1 0 0 0 -1 1v2a1 1 0 0 0 1 1h3",
        ),
      ]),
      svg.path([attribute.attribute("d", "M6 8v3a1 1 0 0 0 1 1h3")]),
      svg.path([attribute.attribute("d", "M10 8v8")]),
    ],
  )
}

/// `number-43-small`
pub fn number_43_small(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([
        attribute.attribute(
          "d",
          "M14 8h2.5a1.5 1.5 0 0 1 1.5 1.5v1a1.5 1.5 0 0 1 -1.5 1.5h-1.5h1.5a1.5 1.5 0 0 1 1.5 1.5v1a1.5 1.5 0 0 1 -1.5 1.5h-2.5",
        ),
      ]),
      svg.path([attribute.attribute("d", "M6 8v3a1 1 0 0 0 1 1h3")]),
      svg.path([attribute.attribute("d", "M10 8v8")]),
    ],
  )
}

/// `number-44-small`
pub fn number_44_small(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([attribute.attribute("d", "M14 8v3a1 1 0 0 0 1 1h3")]),
      svg.path([attribute.attribute("d", "M18 8v8")]),
      svg.path([attribute.attribute("d", "M6 8v3a1 1 0 0 0 1 1h3")]),
      svg.path([attribute.attribute("d", "M10 8v8")]),
    ],
  )
}

/// `number-45-small`
pub fn number_45_small(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([
        attribute.attribute(
          "d",
          "M14 15a1 1 0 0 0 1 1h2a1 1 0 0 0 1 -1v-2a1 1 0 0 0 -1 -1h-3v-4h4",
        ),
      ]),
      svg.path([attribute.attribute("d", "M6 8v3a1 1 0 0 0 1 1h3")]),
      svg.path([attribute.attribute("d", "M10 8v8")]),
    ],
  )
}

/// `number-46-small`
pub fn number_46_small(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([
        attribute.attribute(
          "d",
          "M18 9a1 1 0 0 0 -1 -1h-2a1 1 0 0 0 -1 1v6a1 1 0 0 0 1 1h2a1 1 0 0 0 1 -1v-2a1 1 0 0 0 -1 -1h-3",
        ),
      ]),
      svg.path([attribute.attribute("d", "M6 8v3a1 1 0 0 0 1 1h3")]),
      svg.path([attribute.attribute("d", "M10 8v8")]),
    ],
  )
}

/// `number-47-small`
pub fn number_47_small(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([attribute.attribute("d", "M14 8h4l-2 8")]),
      svg.path([attribute.attribute("d", "M6 8v3a1 1 0 0 0 1 1h3")]),
      svg.path([attribute.attribute("d", "M10 8v8")]),
    ],
  )
}

/// `number-48-small`
pub fn number_48_small(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([
        attribute.attribute(
          "d",
          "M16 12h-1a1 1 0 0 1 -1 -1v-2a1 1 0 0 1 1 -1h2a1 1 0 0 1 1 1v2a1 1 0 0 1 -1 1h-2a1 1 0 0 0 -1 1v2a1 1 0 0 0 1 1h2a1 1 0 0 0 1 -1v-2a1 1 0 0 0 -1 -1",
        ),
      ]),
      svg.path([attribute.attribute("d", "M6 8v3a1 1 0 0 0 1 1h3")]),
      svg.path([attribute.attribute("d", "M10 8v8")]),
    ],
  )
}

/// `number-49-small`
pub fn number_49_small(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([
        attribute.attribute(
          "d",
          "M14 15a1 1 0 0 0 1 1h2a1 1 0 0 0 1 -1v-6a1 1 0 0 0 -1 -1h-2a1 1 0 0 0 -1 1v2a1 1 0 0 0 1 1h3",
        ),
      ]),
      svg.path([attribute.attribute("d", "M6 8v3a1 1 0 0 0 1 1h3")]),
      svg.path([attribute.attribute("d", "M10 8v8")]),
    ],
  )
}

/// `number-4-small`
pub fn number_4_small(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([attribute.attribute("d", "M10 8v3a1 1 0 0 0 1 1h3")]),
      svg.path([attribute.attribute("d", "M14 8v8")]),
    ],
  )
}

/// `number-5`
pub fn number_5(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([attribute.attribute("d", "M8 20h4a4 4 0 1 0 0 -8h-4v-8h8")]),
    ],
  )
}

/// `number-50-small`
pub fn number_50_small(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([
        attribute.attribute("d", "M14 10v4a2 2 0 1 0 4 0v-4a2 2 0 1 0 -4 0"),
      ]),
      svg.path([
        attribute.attribute(
          "d",
          "M6 15a1 1 0 0 0 1 1h2a1 1 0 0 0 1 -1v-2a1 1 0 0 0 -1 -1h-3v-4h4",
        ),
      ]),
    ],
  )
}

/// `number-51-small`
pub fn number_51_small(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([attribute.attribute("d", "M15 8h1v8")]),
      svg.path([
        attribute.attribute(
          "d",
          "M7 15a1 1 0 0 0 1 1h2a1 1 0 0 0 1 -1v-2a1 1 0 0 0 -1 -1h-3v-4h4",
        ),
      ]),
    ],
  )
}

/// `number-52-small`
pub fn number_52_small(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([
        attribute.attribute(
          "d",
          "M14 8h3a1 1 0 0 1 1 1v2a1 1 0 0 1 -1 1h-2a1 1 0 0 0 -1 1v2a1 1 0 0 0 1 1h3",
        ),
      ]),
      svg.path([
        attribute.attribute(
          "d",
          "M6 15a1 1 0 0 0 1 1h2a1 1 0 0 0 1 -1v-2a1 1 0 0 0 -1 -1h-3v-4h4",
        ),
      ]),
    ],
  )
}

/// `number-53-small`
pub fn number_53_small(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([
        attribute.attribute(
          "d",
          "M14 8h2.5a1.5 1.5 0 0 1 1.5 1.5v1a1.5 1.5 0 0 1 -1.5 1.5h-1.5h1.5a1.5 1.5 0 0 1 1.5 1.5v1a1.5 1.5 0 0 1 -1.5 1.5h-2.5",
        ),
      ]),
      svg.path([
        attribute.attribute(
          "d",
          "M6 15a1 1 0 0 0 1 1h2a1 1 0 0 0 1 -1v-2a1 1 0 0 0 -1 -1h-3v-4h4",
        ),
      ]),
    ],
  )
}

/// `number-54-small`
pub fn number_54_small(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([attribute.attribute("d", "M14 8v3a1 1 0 0 0 1 1h3")]),
      svg.path([attribute.attribute("d", "M18 8v8")]),
      svg.path([
        attribute.attribute(
          "d",
          "M6 15a1 1 0 0 0 1 1h2a1 1 0 0 0 1 -1v-2a1 1 0 0 0 -1 -1h-3v-4h4",
        ),
      ]),
    ],
  )
}

/// `number-55-small`
pub fn number_55_small(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([
        attribute.attribute(
          "d",
          "M14 15a1 1 0 0 0 1 1h2a1 1 0 0 0 1 -1v-2a1 1 0 0 0 -1 -1h-3v-4h4",
        ),
      ]),
      svg.path([
        attribute.attribute(
          "d",
          "M6 15a1 1 0 0 0 1 1h2a1 1 0 0 0 1 -1v-2a1 1 0 0 0 -1 -1h-3v-4h4",
        ),
      ]),
    ],
  )
}

/// `number-56-small`
pub fn number_56_small(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([
        attribute.attribute(
          "d",
          "M18 9a1 1 0 0 0 -1 -1h-2a1 1 0 0 0 -1 1v6a1 1 0 0 0 1 1h2a1 1 0 0 0 1 -1v-2a1 1 0 0 0 -1 -1h-3",
        ),
      ]),
      svg.path([
        attribute.attribute(
          "d",
          "M6 15a1 1 0 0 0 1 1h2a1 1 0 0 0 1 -1v-2a1 1 0 0 0 -1 -1h-3v-4h4",
        ),
      ]),
    ],
  )
}

/// `number-57-small`
pub fn number_57_small(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([attribute.attribute("d", "M14 8h4l-2 8")]),
      svg.path([
        attribute.attribute(
          "d",
          "M6 15a1 1 0 0 0 1 1h2a1 1 0 0 0 1 -1v-2a1 1 0 0 0 -1 -1h-3v-4h4",
        ),
      ]),
    ],
  )
}

/// `number-58-small`
pub fn number_58_small(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([
        attribute.attribute(
          "d",
          "M16 12h-1a1 1 0 0 1 -1 -1v-2a1 1 0 0 1 1 -1h2a1 1 0 0 1 1 1v2a1 1 0 0 1 -1 1h-2a1 1 0 0 0 -1 1v2a1 1 0 0 0 1 1h2a1 1 0 0 0 1 -1v-2a1 1 0 0 0 -1 -1",
        ),
      ]),
      svg.path([
        attribute.attribute(
          "d",
          "M6 15a1 1 0 0 0 1 1h2a1 1 0 0 0 1 -1v-2a1 1 0 0 0 -1 -1h-3v-4h4",
        ),
      ]),
    ],
  )
}

/// `number-59-small`
pub fn number_59_small(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([
        attribute.attribute(
          "d",
          "M14 15a1 1 0 0 0 1 1h2a1 1 0 0 0 1 -1v-6a1 1 0 0 0 -1 -1h-2a1 1 0 0 0 -1 1v2a1 1 0 0 0 1 1h3",
        ),
      ]),
      svg.path([
        attribute.attribute(
          "d",
          "M6 15a1 1 0 0 0 1 1h2a1 1 0 0 0 1 -1v-2a1 1 0 0 0 -1 -1h-3v-4h4",
        ),
      ]),
    ],
  )
}

/// `number-5-small`
pub fn number_5_small(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([
        attribute.attribute(
          "d",
          "M10 15a1 1 0 0 0 1 1h2a1 1 0 0 0 1 -1v-2a1 1 0 0 0 -1 -1h-3v-4h4",
        ),
      ]),
    ],
  )
}

/// `number-6`
pub fn number_6(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([
        attribute.attribute("d", "M8 16a4 4 0 1 0 8 0v-1a4 4 0 1 0 -8 0"),
      ]),
      svg.path([attribute.attribute("d", "M16 8a4 4 0 1 0 -8 0v8")]),
    ],
  )
}

/// `number-60-small`
pub fn number_60_small(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([
        attribute.attribute("d", "M14 10v4a2 2 0 1 0 4 0v-4a2 2 0 1 0 -4 0"),
      ]),
      svg.path([
        attribute.attribute(
          "d",
          "M10 9a1 1 0 0 0 -1 -1h-2a1 1 0 0 0 -1 1v6a1 1 0 0 0 1 1h2a1 1 0 0 0 1 -1v-2a1 1 0 0 0 -1 -1h-3",
        ),
      ]),
    ],
  )
}

/// `number-61-small`
pub fn number_61_small(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([attribute.attribute("d", "M15 8h1v8")]),
      svg.path([
        attribute.attribute(
          "d",
          "M11 9a1 1 0 0 0 -1 -1h-2a1 1 0 0 0 -1 1v6a1 1 0 0 0 1 1h2a1 1 0 0 0 1 -1v-2a1 1 0 0 0 -1 -1h-3",
        ),
      ]),
    ],
  )
}

/// `number-62-small`
pub fn number_62_small(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([
        attribute.attribute(
          "d",
          "M14 8h3a1 1 0 0 1 1 1v2a1 1 0 0 1 -1 1h-2a1 1 0 0 0 -1 1v2a1 1 0 0 0 1 1h3",
        ),
      ]),
      svg.path([
        attribute.attribute(
          "d",
          "M10 9a1 1 0 0 0 -1 -1h-2a1 1 0 0 0 -1 1v6a1 1 0 0 0 1 1h2a1 1 0 0 0 1 -1v-2a1 1 0 0 0 -1 -1h-3",
        ),
      ]),
    ],
  )
}

/// `number-63-small`
pub fn number_63_small(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([
        attribute.attribute(
          "d",
          "M14 8h2.5a1.5 1.5 0 0 1 1.5 1.5v1a1.5 1.5 0 0 1 -1.5 1.5h-1.5h1.5a1.5 1.5 0 0 1 1.5 1.5v1a1.5 1.5 0 0 1 -1.5 1.5h-2.5",
        ),
      ]),
      svg.path([
        attribute.attribute(
          "d",
          "M10 9a1 1 0 0 0 -1 -1h-2a1 1 0 0 0 -1 1v6a1 1 0 0 0 1 1h2a1 1 0 0 0 1 -1v-2a1 1 0 0 0 -1 -1h-3",
        ),
      ]),
    ],
  )
}

/// `number-64-small`
pub fn number_64_small(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([attribute.attribute("d", "M14 8v3a1 1 0 0 0 1 1h3")]),
      svg.path([attribute.attribute("d", "M18 8v8")]),
      svg.path([
        attribute.attribute(
          "d",
          "M10 9a1 1 0 0 0 -1 -1h-2a1 1 0 0 0 -1 1v6a1 1 0 0 0 1 1h2a1 1 0 0 0 1 -1v-2a1 1 0 0 0 -1 -1h-3",
        ),
      ]),
    ],
  )
}

/// `number-65-small`
pub fn number_65_small(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([
        attribute.attribute(
          "d",
          "M14 15a1 1 0 0 0 1 1h2a1 1 0 0 0 1 -1v-2a1 1 0 0 0 -1 -1h-3v-4h4",
        ),
      ]),
      svg.path([
        attribute.attribute(
          "d",
          "M10 9a1 1 0 0 0 -1 -1h-2a1 1 0 0 0 -1 1v6a1 1 0 0 0 1 1h2a1 1 0 0 0 1 -1v-2a1 1 0 0 0 -1 -1h-3",
        ),
      ]),
    ],
  )
}

/// `number-66-small`
pub fn number_66_small(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([
        attribute.attribute(
          "d",
          "M18 9a1 1 0 0 0 -1 -1h-2a1 1 0 0 0 -1 1v6a1 1 0 0 0 1 1h2a1 1 0 0 0 1 -1v-2a1 1 0 0 0 -1 -1h-3",
        ),
      ]),
      svg.path([
        attribute.attribute(
          "d",
          "M10 9a1 1 0 0 0 -1 -1h-2a1 1 0 0 0 -1 1v6a1 1 0 0 0 1 1h2a1 1 0 0 0 1 -1v-2a1 1 0 0 0 -1 -1h-3",
        ),
      ]),
    ],
  )
}

/// `number-67-small`
pub fn number_67_small(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([attribute.attribute("d", "M14 8h4l-2 8")]),
      svg.path([
        attribute.attribute(
          "d",
          "M10 9a1 1 0 0 0 -1 -1h-2a1 1 0 0 0 -1 1v6a1 1 0 0 0 1 1h2a1 1 0 0 0 1 -1v-2a1 1 0 0 0 -1 -1h-3",
        ),
      ]),
    ],
  )
}

/// `number-68-small`
pub fn number_68_small(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([
        attribute.attribute(
          "d",
          "M16 12h-1a1 1 0 0 1 -1 -1v-2a1 1 0 0 1 1 -1h2a1 1 0 0 1 1 1v2a1 1 0 0 1 -1 1h-2a1 1 0 0 0 -1 1v2a1 1 0 0 0 1 1h2a1 1 0 0 0 1 -1v-2a1 1 0 0 0 -1 -1",
        ),
      ]),
      svg.path([
        attribute.attribute(
          "d",
          "M10 9a1 1 0 0 0 -1 -1h-2a1 1 0 0 0 -1 1v6a1 1 0 0 0 1 1h2a1 1 0 0 0 1 -1v-2a1 1 0 0 0 -1 -1h-3",
        ),
      ]),
    ],
  )
}

/// `number-69-small`
pub fn number_69_small(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([
        attribute.attribute(
          "d",
          "M14 15a1 1 0 0 0 1 1h2a1 1 0 0 0 1 -1v-6a1 1 0 0 0 -1 -1h-2a1 1 0 0 0 -1 1v2a1 1 0 0 0 1 1h3",
        ),
      ]),
      svg.path([
        attribute.attribute(
          "d",
          "M10 9a1 1 0 0 0 -1 -1h-2a1 1 0 0 0 -1 1v6a1 1 0 0 0 1 1h2a1 1 0 0 0 1 -1v-2a1 1 0 0 0 -1 -1h-3",
        ),
      ]),
    ],
  )
}

/// `number-6-small`
pub fn number_6_small(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([
        attribute.attribute(
          "d",
          "M14 9a1 1 0 0 0 -1 -1h-2a1 1 0 0 0 -1 1v6a1 1 0 0 0 1 1h2a1 1 0 0 0 1 -1v-2a1 1 0 0 0 -1 -1h-3",
        ),
      ]),
    ],
  )
}

/// `number-7`
pub fn number_7(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [svg.path([attribute.attribute("d", "M8 4h8l-4 16")])],
  )
}

/// `number-70-small`
pub fn number_70_small(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([
        attribute.attribute("d", "M14 10v4a2 2 0 1 0 4 0v-4a2 2 0 1 0 -4 0"),
      ]),
      svg.path([attribute.attribute("d", "M6 8h4l-2 8")]),
    ],
  )
}

/// `number-71-small`
pub fn number_71_small(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([attribute.attribute("d", "M15 8h1v8")]),
      svg.path([attribute.attribute("d", "M7 8h4l-2 8")]),
    ],
  )
}

/// `number-72-small`
pub fn number_72_small(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([
        attribute.attribute(
          "d",
          "M14 8h3a1 1 0 0 1 1 1v2a1 1 0 0 1 -1 1h-2a1 1 0 0 0 -1 1v2a1 1 0 0 0 1 1h3",
        ),
      ]),
      svg.path([attribute.attribute("d", "M6 8h4l-2 8")]),
    ],
  )
}

/// `number-73-small`
pub fn number_73_small(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([
        attribute.attribute(
          "d",
          "M14 8h2.5a1.5 1.5 0 0 1 1.5 1.5v1a1.5 1.5 0 0 1 -1.5 1.5h-1.5h1.5a1.5 1.5 0 0 1 1.5 1.5v1a1.5 1.5 0 0 1 -1.5 1.5h-2.5",
        ),
      ]),
      svg.path([attribute.attribute("d", "M6 8h4l-2 8")]),
    ],
  )
}

/// `number-74-small`
pub fn number_74_small(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([attribute.attribute("d", "M14 8v3a1 1 0 0 0 1 1h3")]),
      svg.path([attribute.attribute("d", "M18 8v8")]),
      svg.path([attribute.attribute("d", "M6 8h4l-2 8")]),
    ],
  )
}

/// `number-75-small`
pub fn number_75_small(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([
        attribute.attribute(
          "d",
          "M14 15a1 1 0 0 0 1 1h2a1 1 0 0 0 1 -1v-2a1 1 0 0 0 -1 -1h-3v-4h4",
        ),
      ]),
      svg.path([attribute.attribute("d", "M6 8h4l-2 8")]),
    ],
  )
}

/// `number-76-small`
pub fn number_76_small(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([
        attribute.attribute(
          "d",
          "M18 9a1 1 0 0 0 -1 -1h-2a1 1 0 0 0 -1 1v6a1 1 0 0 0 1 1h2a1 1 0 0 0 1 -1v-2a1 1 0 0 0 -1 -1h-3",
        ),
      ]),
      svg.path([attribute.attribute("d", "M6 8h4l-2 8")]),
    ],
  )
}

/// `number-77-small`
pub fn number_77_small(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([attribute.attribute("d", "M14 8h4l-2 8")]),
      svg.path([attribute.attribute("d", "M6 8h4l-2 8")]),
    ],
  )
}

/// `number-78-small`
pub fn number_78_small(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([
        attribute.attribute(
          "d",
          "M16 12h-1a1 1 0 0 1 -1 -1v-2a1 1 0 0 1 1 -1h2a1 1 0 0 1 1 1v2a1 1 0 0 1 -1 1h-2a1 1 0 0 0 -1 1v2a1 1 0 0 0 1 1h2a1 1 0 0 0 1 -1v-2a1 1 0 0 0 -1 -1",
        ),
      ]),
      svg.path([attribute.attribute("d", "M6 8h4l-2 8")]),
    ],
  )
}

/// `number-79-small`
pub fn number_79_small(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([
        attribute.attribute(
          "d",
          "M14 15a1 1 0 0 0 1 1h2a1 1 0 0 0 1 -1v-6a1 1 0 0 0 -1 -1h-2a1 1 0 0 0 -1 1v2a1 1 0 0 0 1 1h3",
        ),
      ]),
      svg.path([attribute.attribute("d", "M6 8h4l-2 8")]),
    ],
  )
}

/// `number-7-small`
pub fn number_7_small(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [svg.path([attribute.attribute("d", "M10 8h4l-2 8")])],
  )
}

/// `number-8`
pub fn number_8(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([attribute.attribute("d", "M8 8a4 4 0 1 0 8 0a4 4 0 1 0 -8 0")]),
      svg.path([attribute.attribute("d", "M8 16a4 4 0 1 0 8 0a4 4 0 1 0 -8 0")]),
    ],
  )
}

/// `number-80-small`
pub fn number_80_small(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([
        attribute.attribute("d", "M14 10v4a2 2 0 1 0 4 0v-4a2 2 0 1 0 -4 0"),
      ]),
      svg.path([
        attribute.attribute(
          "d",
          "M8 12h-1a1 1 0 0 1 -1 -1v-2a1 1 0 0 1 1 -1h2a1 1 0 0 1 1 1v2a1 1 0 0 1 -1 1h-2a1 1 0 0 0 -1 1v2a1 1 0 0 0 1 1h2a1 1 0 0 0 1 -1v-2a1 1 0 0 0 -1 -1",
        ),
      ]),
    ],
  )
}

/// `number-81-small`
pub fn number_81_small(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([attribute.attribute("d", "M15 8h1v8")]),
      svg.path([
        attribute.attribute(
          "d",
          "M9 12h-1a1 1 0 0 1 -1 -1v-2a1 1 0 0 1 1 -1h2a1 1 0 0 1 1 1v2a1 1 0 0 1 -1 1h-2a1 1 0 0 0 -1 1v2a1 1 0 0 0 1 1h2a1 1 0 0 0 1 -1v-2a1 1 0 0 0 -1 -1",
        ),
      ]),
    ],
  )
}

/// `number-82-small`
pub fn number_82_small(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([
        attribute.attribute(
          "d",
          "M14 8h3a1 1 0 0 1 1 1v2a1 1 0 0 1 -1 1h-2a1 1 0 0 0 -1 1v2a1 1 0 0 0 1 1h3",
        ),
      ]),
      svg.path([
        attribute.attribute(
          "d",
          "M8 12h-1a1 1 0 0 1 -1 -1v-2a1 1 0 0 1 1 -1h2a1 1 0 0 1 1 1v2a1 1 0 0 1 -1 1h-2a1 1 0 0 0 -1 1v2a1 1 0 0 0 1 1h2a1 1 0 0 0 1 -1v-2a1 1 0 0 0 -1 -1",
        ),
      ]),
    ],
  )
}

/// `number-83-small`
pub fn number_83_small(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([
        attribute.attribute(
          "d",
          "M14 8h2.5a1.5 1.5 0 0 1 1.5 1.5v1a1.5 1.5 0 0 1 -1.5 1.5h-1.5h1.5a1.5 1.5 0 0 1 1.5 1.5v1a1.5 1.5 0 0 1 -1.5 1.5h-2.5",
        ),
      ]),
      svg.path([
        attribute.attribute(
          "d",
          "M8 12h-1a1 1 0 0 1 -1 -1v-2a1 1 0 0 1 1 -1h2a1 1 0 0 1 1 1v2a1 1 0 0 1 -1 1h-2a1 1 0 0 0 -1 1v2a1 1 0 0 0 1 1h2a1 1 0 0 0 1 -1v-2a1 1 0 0 0 -1 -1",
        ),
      ]),
    ],
  )
}

/// `number-84-small`
pub fn number_84_small(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([attribute.attribute("d", "M14 8v3a1 1 0 0 0 1 1h3")]),
      svg.path([attribute.attribute("d", "M18 8v8")]),
      svg.path([
        attribute.attribute(
          "d",
          "M8 12h-1a1 1 0 0 1 -1 -1v-2a1 1 0 0 1 1 -1h2a1 1 0 0 1 1 1v2a1 1 0 0 1 -1 1h-2a1 1 0 0 0 -1 1v2a1 1 0 0 0 1 1h2a1 1 0 0 0 1 -1v-2a1 1 0 0 0 -1 -1",
        ),
      ]),
    ],
  )
}

/// `number-85-small`
pub fn number_85_small(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([
        attribute.attribute(
          "d",
          "M14 15a1 1 0 0 0 1 1h2a1 1 0 0 0 1 -1v-2a1 1 0 0 0 -1 -1h-3v-4h4",
        ),
      ]),
      svg.path([
        attribute.attribute(
          "d",
          "M8 12h-1a1 1 0 0 1 -1 -1v-2a1 1 0 0 1 1 -1h2a1 1 0 0 1 1 1v2a1 1 0 0 1 -1 1h-2a1 1 0 0 0 -1 1v2a1 1 0 0 0 1 1h2a1 1 0 0 0 1 -1v-2a1 1 0 0 0 -1 -1",
        ),
      ]),
    ],
  )
}

/// `number-86-small`
pub fn number_86_small(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([
        attribute.attribute(
          "d",
          "M18 9a1 1 0 0 0 -1 -1h-2a1 1 0 0 0 -1 1v6a1 1 0 0 0 1 1h2a1 1 0 0 0 1 -1v-2a1 1 0 0 0 -1 -1h-3",
        ),
      ]),
      svg.path([
        attribute.attribute(
          "d",
          "M8 12h-1a1 1 0 0 1 -1 -1v-2a1 1 0 0 1 1 -1h2a1 1 0 0 1 1 1v2a1 1 0 0 1 -1 1h-2a1 1 0 0 0 -1 1v2a1 1 0 0 0 1 1h2a1 1 0 0 0 1 -1v-2a1 1 0 0 0 -1 -1",
        ),
      ]),
    ],
  )
}

/// `number-87-small`
pub fn number_87_small(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([attribute.attribute("d", "M14 8h4l-2 8")]),
      svg.path([
        attribute.attribute(
          "d",
          "M8 12h-1a1 1 0 0 1 -1 -1v-2a1 1 0 0 1 1 -1h2a1 1 0 0 1 1 1v2a1 1 0 0 1 -1 1h-2a1 1 0 0 0 -1 1v2a1 1 0 0 0 1 1h2a1 1 0 0 0 1 -1v-2a1 1 0 0 0 -1 -1",
        ),
      ]),
    ],
  )
}

/// `number-88-small`
pub fn number_88_small(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([
        attribute.attribute(
          "d",
          "M16 12h-1a1 1 0 0 1 -1 -1v-2a1 1 0 0 1 1 -1h2a1 1 0 0 1 1 1v2a1 1 0 0 1 -1 1h-2a1 1 0 0 0 -1 1v2a1 1 0 0 0 1 1h2a1 1 0 0 0 1 -1v-2a1 1 0 0 0 -1 -1",
        ),
      ]),
      svg.path([
        attribute.attribute(
          "d",
          "M8 12h-1a1 1 0 0 1 -1 -1v-2a1 1 0 0 1 1 -1h2a1 1 0 0 1 1 1v2a1 1 0 0 1 -1 1h-2a1 1 0 0 0 -1 1v2a1 1 0 0 0 1 1h2a1 1 0 0 0 1 -1v-2a1 1 0 0 0 -1 -1",
        ),
      ]),
    ],
  )
}

/// `number-89-small`
pub fn number_89_small(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([
        attribute.attribute(
          "d",
          "M14 15a1 1 0 0 0 1 1h2a1 1 0 0 0 1 -1v-6a1 1 0 0 0 -1 -1h-2a1 1 0 0 0 -1 1v2a1 1 0 0 0 1 1h3",
        ),
      ]),
      svg.path([
        attribute.attribute(
          "d",
          "M8 12h-1a1 1 0 0 1 -1 -1v-2a1 1 0 0 1 1 -1h2a1 1 0 0 1 1 1v2a1 1 0 0 1 -1 1h-2a1 1 0 0 0 -1 1v2a1 1 0 0 0 1 1h2a1 1 0 0 0 1 -1v-2a1 1 0 0 0 -1 -1",
        ),
      ]),
    ],
  )
}

/// `number-8-small`
pub fn number_8_small(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([
        attribute.attribute(
          "d",
          "M12 12h-1a1 1 0 0 1 -1 -1v-2a1 1 0 0 1 1 -1h2a1 1 0 0 1 1 1v2a1 1 0 0 1 -1 1h-2a1 1 0 0 0 -1 1v2a1 1 0 0 0 1 1h2a1 1 0 0 0 1 -1v-2a1 1 0 0 0 -1 -1",
        ),
      ]),
    ],
  )
}

/// `number-9`
pub fn number_9(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([
        attribute.attribute("d", "M16 8a4 4 0 1 0 -8 0v1a4 4 0 1 0 8 0"),
      ]),
      svg.path([attribute.attribute("d", "M8 16a4 4 0 1 0 8 0v-8")]),
    ],
  )
}

/// `number-90-small`
pub fn number_90_small(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([
        attribute.attribute("d", "M14 10v4a2 2 0 1 0 4 0v-4a2 2 0 1 0 -4 0"),
      ]),
      svg.path([
        attribute.attribute(
          "d",
          "M6 15a1 1 0 0 0 1 1h2a1 1 0 0 0 1 -1v-6a1 1 0 0 0 -1 -1h-2a1 1 0 0 0 -1 1v2a1 1 0 0 0 1 1h3",
        ),
      ]),
    ],
  )
}

/// `number-91-small`
pub fn number_91_small(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([attribute.attribute("d", "M15 8h1v8")]),
      svg.path([
        attribute.attribute(
          "d",
          "M7 15a1 1 0 0 0 1 1h2a1 1 0 0 0 1 -1v-6a1 1 0 0 0 -1 -1h-2a1 1 0 0 0 -1 1v2a1 1 0 0 0 1 1h3",
        ),
      ]),
    ],
  )
}

/// `number-92-small`
pub fn number_92_small(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([
        attribute.attribute(
          "d",
          "M14 8h3a1 1 0 0 1 1 1v2a1 1 0 0 1 -1 1h-2a1 1 0 0 0 -1 1v2a1 1 0 0 0 1 1h3",
        ),
      ]),
      svg.path([
        attribute.attribute(
          "d",
          "M6 15a1 1 0 0 0 1 1h2a1 1 0 0 0 1 -1v-6a1 1 0 0 0 -1 -1h-2a1 1 0 0 0 -1 1v2a1 1 0 0 0 1 1h3",
        ),
      ]),
    ],
  )
}

/// `number-93-small`
pub fn number_93_small(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([
        attribute.attribute(
          "d",
          "M14 8h2.5a1.5 1.5 0 0 1 1.5 1.5v1a1.5 1.5 0 0 1 -1.5 1.5h-1.5h1.5a1.5 1.5 0 0 1 1.5 1.5v1a1.5 1.5 0 0 1 -1.5 1.5h-2.5",
        ),
      ]),
      svg.path([
        attribute.attribute(
          "d",
          "M6 15a1 1 0 0 0 1 1h2a1 1 0 0 0 1 -1v-6a1 1 0 0 0 -1 -1h-2a1 1 0 0 0 -1 1v2a1 1 0 0 0 1 1h3",
        ),
      ]),
    ],
  )
}

/// `number-94-small`
pub fn number_94_small(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([attribute.attribute("d", "M14 8v3a1 1 0 0 0 1 1h3")]),
      svg.path([attribute.attribute("d", "M18 8v8")]),
      svg.path([
        attribute.attribute(
          "d",
          "M6 15a1 1 0 0 0 1 1h2a1 1 0 0 0 1 -1v-6a1 1 0 0 0 -1 -1h-2a1 1 0 0 0 -1 1v2a1 1 0 0 0 1 1h3",
        ),
      ]),
    ],
  )
}

/// `number-95-small`
pub fn number_95_small(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([
        attribute.attribute(
          "d",
          "M14 15a1 1 0 0 0 1 1h2a1 1 0 0 0 1 -1v-2a1 1 0 0 0 -1 -1h-3v-4h4",
        ),
      ]),
      svg.path([
        attribute.attribute(
          "d",
          "M6 15a1 1 0 0 0 1 1h2a1 1 0 0 0 1 -1v-6a1 1 0 0 0 -1 -1h-2a1 1 0 0 0 -1 1v2a1 1 0 0 0 1 1h3",
        ),
      ]),
    ],
  )
}

/// `number-96-small`
pub fn number_96_small(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([
        attribute.attribute(
          "d",
          "M18 9a1 1 0 0 0 -1 -1h-2a1 1 0 0 0 -1 1v6a1 1 0 0 0 1 1h2a1 1 0 0 0 1 -1v-2a1 1 0 0 0 -1 -1h-3",
        ),
      ]),
      svg.path([
        attribute.attribute(
          "d",
          "M6 15a1 1 0 0 0 1 1h2a1 1 0 0 0 1 -1v-6a1 1 0 0 0 -1 -1h-2a1 1 0 0 0 -1 1v2a1 1 0 0 0 1 1h3",
        ),
      ]),
    ],
  )
}

/// `number-97-small`
pub fn number_97_small(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([attribute.attribute("d", "M14 8h4l-2 8")]),
      svg.path([
        attribute.attribute(
          "d",
          "M6 15a1 1 0 0 0 1 1h2a1 1 0 0 0 1 -1v-6a1 1 0 0 0 -1 -1h-2a1 1 0 0 0 -1 1v2a1 1 0 0 0 1 1h3",
        ),
      ]),
    ],
  )
}

/// `number-98-small`
pub fn number_98_small(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([
        attribute.attribute(
          "d",
          "M16 12h-1a1 1 0 0 1 -1 -1v-2a1 1 0 0 1 1 -1h2a1 1 0 0 1 1 1v2a1 1 0 0 1 -1 1h-2a1 1 0 0 0 -1 1v2a1 1 0 0 0 1 1h2a1 1 0 0 0 1 -1v-2a1 1 0 0 0 -1 -1",
        ),
      ]),
      svg.path([
        attribute.attribute(
          "d",
          "M6 15a1 1 0 0 0 1 1h2a1 1 0 0 0 1 -1v-6a1 1 0 0 0 -1 -1h-2a1 1 0 0 0 -1 1v2a1 1 0 0 0 1 1h3",
        ),
      ]),
    ],
  )
}

/// `number-99-small`
pub fn number_99_small(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([
        attribute.attribute(
          "d",
          "M14 15a1 1 0 0 0 1 1h2a1 1 0 0 0 1 -1v-6a1 1 0 0 0 -1 -1h-2a1 1 0 0 0 -1 1v2a1 1 0 0 0 1 1h3",
        ),
      ]),
      svg.path([
        attribute.attribute(
          "d",
          "M6 15a1 1 0 0 0 1 1h2a1 1 0 0 0 1 -1v-6a1 1 0 0 0 -1 -1h-2a1 1 0 0 0 -1 1v2a1 1 0 0 0 1 1h3",
        ),
      ]),
    ],
  )
}

/// `number-9-small`
pub fn number_9_small(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([
        attribute.attribute(
          "d",
          "M10 15a1 1 0 0 0 1 1h2a1 1 0 0 0 1 -1v-6a1 1 0 0 0 -1 -1h-2a1 1 0 0 0 -1 1v2a1 1 0 0 0 1 1h3",
        ),
      ]),
    ],
  )
}

/// `numbers`
pub fn numbers(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([attribute.attribute("d", "M8 10v-7l-2 2")]),
      svg.path([
        attribute.attribute(
          "d",
          "M6 16a2 2 0 1 1 4 0c0 .591 -.601 1.46 -1 2l-3 3h4",
        ),
      ]),
      svg.path([
        attribute.attribute("d", "M15 14a2 2 0 1 0 2 -2a2 2 0 1 0 -2 -2"),
      ]),
      svg.path([attribute.attribute("d", "M6.5 10h3")]),
    ],
  )
}

/// `nurse`
pub fn nurse(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([
        attribute.attribute(
          "d",
          "M12 5c2.941 0 6.685 1.537 9 3l-2 11h-14l-2 -11c2.394 -1.513 6.168 -3.005 9 -3",
        ),
      ]),
      svg.path([attribute.attribute("d", "M10 12h4")]),
      svg.path([attribute.attribute("d", "M12 10v4")]),
    ],
  )
}

/// `nut`
pub fn nut(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.outline_defaults,
    attrs: attrs,
    children: [
      svg.path([
        attribute.attribute(
          "d",
          "M19 6.84a2.007 2.007 0 0 1 1 1.754v6.555c0 .728 -.394 1.4 -1.03 1.753l-6 3.844a1.995 1.995 0 0 1 -1.94 0l-6 -3.844a2.006 2.006 0 0 1 -1.03 -1.752v-6.557c0 -.728 .394 -1.399 1.03 -1.753l6 -3.582a2.049 2.049 0 0 1 2 0l6 3.582h-.03",
        ),
      ]),
      svg.path([attribute.attribute("d", "M9 12a3 3 0 1 0 6 0a3 3 0 1 0 -6 0")]),
    ],
  )
}
