//// tabler · filled · shard "m". GENERATED by gg_icon_gen — do not hand-edit.

import gg_icon/icon
import gg_icons_tabler/internal
import lustre/attribute.{type Attribute}
import lustre/element.{type Element}
import lustre/element/svg

/// `macro`
pub fn macro_(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.filled_defaults,
    attrs: attrs,
    children: [
      svg.path([
        attribute.attribute(
          "d",
          "M17.994 2.888l.006 .112v3a6 6 0 0 1 -5 5.916v4.186a6.98 6.98 0 0 1 5 -2.102a1 1 0 0 1 1 1a7 7 0 0 1 -14 0a1 1 0 0 1 1 -1c1.96 0 3.731 .805 5.002 2.103l-.002 -4.186a6 6 0 0 1 -5 -5.917v-3a1 1 0 0 1 1.555 -.832l2.317 1.544l1.42 -1.42a1 1 0 0 1 1.32 -.082l.095 .083l1.42 1.419l2.318 -1.544a1 1 0 0 1 1.55 .72m-10.865 13.24l.03 .134a5.01 5.01 0 0 0 3.71 3.61a5 5 0 0 0 -3.74 -3.744m9.742 .002l-.134 .03a5.01 5.01 0 0 0 -3.61 3.71a5 5 0 0 0 3.744 -3.74",
        ),
      ]),
    ],
  )
}

/// `magnet`
pub fn magnet(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.filled_defaults,
    attrs: attrs,
    children: [
      svg.path([
        attribute.attribute(
          "d",
          "M21 9v4a9 9 0 0 1 -18 0v-4h7v4a2 2 0 1 0 4 0v-4zm-3 -7a3 3 0 0 1 3 3v2h-7v-2a3 3 0 0 1 3 -3zm-11 0a3 3 0 0 1 3 3v2h-7v-2a3 3 0 0 1 3 -3z",
        ),
      ]),
    ],
  )
}

/// `mail`
pub fn mail(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.filled_defaults,
    attrs: attrs,
    children: [
      svg.path([
        attribute.attribute(
          "d",
          "M22 7.535v9.465a3 3 0 0 1 -2.824 2.995l-.176 .005h-14a3 3 0 0 1 -2.995 -2.824l-.005 -.176v-9.465l9.445 6.297l.116 .066a1 1 0 0 0 .878 0l.116 -.066l9.445 -6.297z",
        ),
      ]),
      svg.path([
        attribute.attribute(
          "d",
          "M19 4c1.08 0 2.027 .57 2.555 1.427l-9.555 6.37l-9.555 -6.37a2.999 2.999 0 0 1 2.354 -1.42l.201 -.007h14z",
        ),
      ]),
    ],
  )
}

/// `mail-opened`
pub fn mail_opened(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.filled_defaults,
    attrs: attrs,
    children: [
      svg.path([
        attribute.attribute(
          "d",
          "M14.872 14.287l6.522 6.52a2.996 2.996 0 0 1 -2.218 1.188l-.176 .005h-14a2.995 2.995 0 0 1 -2.394 -1.191l6.521 -6.522l2.318 1.545l.116 .066a1 1 0 0 0 .878 0l.116 -.066l2.317 -1.545z",
        ),
      ]),
      svg.path([attribute.attribute("d", "M2 9.535l5.429 3.62l-5.429 5.43z")]),
      svg.path([attribute.attribute("d", "M22 9.535v9.05l-5.43 -5.43z")]),
      svg.path([
        attribute.attribute(
          "d",
          "M12.44 2.102l.115 .066l8.444 5.629l-8.999 6l-9 -6l8.445 -5.63a1 1 0 0 1 .994 -.065z",
        ),
      ]),
    ],
  )
}

/// `man`
pub fn man(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.filled_defaults,
    attrs: attrs,
    children: [
      svg.path([
        attribute.attribute(
          "d",
          "M15 8c1.628 0 3.2 .787 4.707 2.293a1 1 0 0 1 -1.414 1.414c-.848 -.848 -1.662 -1.369 -2.444 -1.587l-.849 5.944v4.936a1 1 0 0 1 -2 0v-4h-2v4a1 1 0 0 1 -2 0v-4.929l-.85 -5.951c-.781 .218 -1.595 .739 -2.443 1.587a1 1 0 1 1 -1.414 -1.414c1.506 -1.506 3.08 -2.293 4.707 -2.293z",
        ),
      ]),
      svg.path([
        attribute.attribute(
          "d",
          "M12 1a3 3 0 1 1 -3 3l.005 -.176a3 3 0 0 1 2.995 -2.824",
        ),
      ]),
    ],
  )
}

/// `manual-gearbox`
pub fn manual_gearbox(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.filled_defaults,
    attrs: attrs,
    children: [
      svg.path([
        attribute.attribute(
          "d",
          "M19 3a3 3 0 0 1 1 5.829v1.171a3 3 0 0 1 -3 3h-4v2.171a3.001 3.001 0 1 1 -4 2.829l.005 -.176a3 3 0 0 1 1.995 -2.654v-2.17h-5v2.171a3.001 3.001 0 1 1 -4 2.829l.005 -.176a3 3 0 0 1 1.995 -2.654v-6.341a3 3 0 0 1 -2 -2.829l.005 -.176a3 3 0 1 1 3.996 3.005l-.001 2.171h5v-2.17a3 3 0 0 1 -2 -2.83l.005 -.176a3 3 0 1 1 3.996 3.005l-.001 2.171h4a1 1 0 0 0 1 -1v-1.17a3 3 0 0 1 -2 -2.83l.005 -.176a3 3 0 0 1 2.995 -2.824",
        ),
      ]),
    ],
  )
}

/// `map-pin`
pub fn map_pin(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.filled_defaults,
    attrs: attrs,
    children: [
      svg.path([
        attribute.attribute(
          "d",
          "M18.364 4.636a9 9 0 0 1 .203 12.519l-.203 .21l-4.243 4.242a3 3 0 0 1 -4.097 .135l-.144 -.135l-4.244 -4.243a9 9 0 0 1 12.728 -12.728zm-6.364 3.364a3 3 0 1 0 0 6a3 3 0 0 0 0 -6",
        ),
      ]),
    ],
  )
}

/// `medical-cross`
pub fn medical_cross(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.filled_defaults,
    attrs: attrs,
    children: [
      svg.path([
        attribute.attribute(
          "d",
          "M11 2l-.15 .005a2 2 0 0 0 -1.85 1.995v2.803l-2.428 -1.401a2 2 0 0 0 -2.732 .732l-1 1.732l-.073 .138a2 2 0 0 0 .805 2.594l2.427 1.402l-2.427 1.402a2 2 0 0 0 -.732 2.732l1 1.732l.083 .132a2 2 0 0 0 2.649 .6l2.428 -1.402v2.804a2 2 0 0 0 2 2h2l.15 -.005a2 2 0 0 0 1.85 -1.995v-2.804l2.428 1.403a2 2 0 0 0 2.732 -.732l1 -1.732l.073 -.138a2 2 0 0 0 -.805 -2.594l-2.428 -1.403l2.428 -1.402a2 2 0 0 0 .732 -2.732l-1 -1.732l-.083 -.132a2 2 0 0 0 -2.649 -.6l-2.428 1.4v-2.802a2 2 0 0 0 -2 -2h-2z",
        ),
      ]),
    ],
  )
}

/// `meeple`
pub fn meeple(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.filled_defaults,
    attrs: attrs,
    children: [
      svg.path([
        attribute.attribute(
          "d",
          "M12 2c2.486 0 3.713 1.766 3.955 4.1l.01 .124l.129 .036c3.17 .928 5.754 2.487 5.9 4.556l.006 .184c0 1.427 -1.297 2.322 -2.871 2.733l-.201 .049l.026 .03c.244 .276 .532 .603 .7 .797l.057 .066c.49 .573 .884 1.073 1.216 1.56c.69 1.01 1.073 1.904 1.073 2.765a2 2 0 0 1 -2 2h-5c-1.043 0 -1.344 -.453 -2.394 -2.553c-.29 -.58 -.448 -.882 -.593 -1.118l-.013 -.022l-.013 .022c-.129 .21 -.268 .472 -.5 .935l-.093 .183c-1.05 2.1 -1.351 2.553 -2.394 2.553h-5a2 2 0 0 1 -2 -2c0 -.86 .384 -1.755 1.073 -2.765a18 18 0 0 1 1.216 -1.56c.152 -.178 .482 -.553 .757 -.863l.025 -.03l-.2 -.049c-1.506 -.393 -2.758 -1.23 -2.864 -2.55l-.007 -.183c0 -2.16 2.643 -3.785 5.906 -4.74l.128 -.036l.011 -.124c.235 -2.26 1.394 -3.99 3.726 -4.095z",
        ),
      ]),
    ],
  )
}

/// `melon`
pub fn melon(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.filled_defaults,
    attrs: attrs,
    children: [
      svg.path([
        attribute.attribute(
          "d",
          "M16.77 2.62a1 1 0 0 1 1.436 .055a10.96 10.96 0 0 1 2.794 7.326c0 6.074 -4.925 10.999 -10.999 10.999a10.97 10.97 0 0 1 -7.684 -3.127a1 1 0 0 1 .008 -1.438l4.343 -4.153a1 1 0 0 1 1.352 -.027a3 3 0 0 0 4.32 -4.133a1 1 0 0 1 .088 -1.35z",
        ),
      ]),
    ],
  )
}

/// `menu-2`
pub fn menu_2(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.filled_defaults,
    attrs: attrs,
    children: [
      svg.path([
        attribute.attribute(
          "d",
          "M21 6a1 1 0 0 1 -1 1h-16a1 1 0 1 1 0 -2h16a1 1 0 0 1 1 1",
        ),
      ]),
      svg.path([
        attribute.attribute(
          "d",
          "M21 12a1 1 0 0 1 -1 1h-16a1 1 0 0 1 0 -2h16a1 1 0 0 1 1 1",
        ),
      ]),
      svg.path([
        attribute.attribute(
          "d",
          "M21 18a1 1 0 0 1 -1 1h-16a1 1 0 0 1 0 -2h16a1 1 0 0 1 1 1",
        ),
      ]),
    ],
  )
}

/// `message`
pub fn message(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.filled_defaults,
    attrs: attrs,
    children: [
      svg.path([
        attribute.attribute(
          "d",
          "M18 3a4 4 0 0 1 4 4v8a4 4 0 0 1 -4 4h-4.724l-4.762 2.857a1 1 0 0 1 -1.508 -.743l-.006 -.114v-2h-1a4 4 0 0 1 -3.995 -3.8l-.005 -.2v-8a4 4 0 0 1 4 -4zm-4 9h-6a1 1 0 0 0 0 2h6a1 1 0 0 0 0 -2m2 -4h-8a1 1 0 1 0 0 2h8a1 1 0 0 0 0 -2",
        ),
      ]),
    ],
  )
}

/// `message-2`
pub fn message_2(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.filled_defaults,
    attrs: attrs,
    children: [
      svg.path([
        attribute.attribute(
          "d",
          "M18 3a4 4 0 0 1 4 4v8a4 4 0 0 1 -4 4h-2.586l-2.707 2.707a1 1 0 0 1 -1.32 .083l-.094 -.083l-2.708 -2.707h-2.585a4 4 0 0 1 -3.995 -3.8l-.005 -.2v-8a4 4 0 0 1 4 -4zm-4 9h-6a1 1 0 0 0 0 2h6a1 1 0 0 0 0 -2m2 -4h-8a1 1 0 1 0 0 2h8a1 1 0 0 0 0 -2",
        ),
      ]),
    ],
  )
}

/// `message-chatbot`
pub fn message_chatbot(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.filled_defaults,
    attrs: attrs,
    children: [
      svg.path([
        attribute.attribute(
          "d",
          "M18 3a4 4 0 0 1 4 4v8a4 4 0 0 1 -4 4h-4.724l-4.762 2.857a1 1 0 0 1 -1.508 -.743l-.006 -.114v-2h-1a4 4 0 0 1 -3.995 -3.8l-.005 -.2v-8a4 4 0 0 1 4 -4zm-2.8 9.286a1 1 0 0 0 -1.414 .014a2.5 2.5 0 0 1 -3.572 0a1 1 0 0 0 -1.428 1.4a4.5 4.5 0 0 0 6.428 0a1 1 0 0 0 -.014 -1.414m-5.69 -4.286h-.01a1 1 0 1 0 0 2h.01a1 1 0 0 0 0 -2m5 0h-.01a1 1 0 0 0 0 2h.01a1 1 0 0 0 0 -2",
        ),
      ]),
    ],
  )
}

/// `message-circle`
pub fn message_circle(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.filled_defaults,
    attrs: attrs,
    children: [
      svg.path([
        attribute.attribute(
          "d",
          "M5.821 4.91c3.899 -2.765 9.468 -2.539 13.073 .535c3.667 3.129 4.168 8.238 1.152 11.898c-2.841 3.447 -7.965 4.583 -12.231 2.805l-.233 -.101l-4.374 .931l-.04 .006l-.035 .007h-.018l-.022 .005h-.038l-.033 .004l-.021 -.001l-.023 .001l-.033 -.003h-.035l-.022 -.004l-.022 -.002l-.035 -.007l-.034 -.005l-.016 -.004l-.024 -.005l-.049 -.016l-.024 -.005l-.011 -.005l-.022 -.007l-.045 -.02l-.03 -.012l-.011 -.006l-.014 -.006l-.031 -.018l-.045 -.024l-.016 -.011l-.037 -.026l-.04 -.027l-.002 -.004l-.013 -.009l-.043 -.04l-.025 -.02l-.006 -.007l-.056 -.062l-.013 -.014l-.011 -.014l-.039 -.056l-.014 -.019l-.005 -.01l-.042 -.073l-.007 -.012l-.004 -.008l-.007 -.012l-.014 -.038l-.02 -.042l-.004 -.016l-.004 -.01l-.017 -.061l-.007 -.018l-.002 -.015l-.005 -.019l-.005 -.033l-.008 -.042l-.002 -.031l-.003 -.01v-.016l-.004 -.054l.001 -.036l.001 -.023l.002 -.053l.004 -.025v-.019l.008 -.035l.005 -.034l.005 -.02l.004 -.02l.018 -.06l.003 -.013l1.15 -3.45l-.022 -.037c-2.21 -3.747 -1.209 -8.391 2.413 -11.119z",
        ),
      ]),
    ],
  )
}

/// `message-report`
pub fn message_report(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.filled_defaults,
    attrs: attrs,
    children: [
      svg.path([
        attribute.attribute(
          "d",
          "M18 3a4 4 0 0 1 4 4v8a4 4 0 0 1 -4 4h-4.724l-4.762 2.857a1 1 0 0 1 -1.508 -.743l-.006 -.114v-2h-1a4 4 0 0 1 -3.995 -3.8l-.005 -.2v-8a4 4 0 0 1 4 -4zm-6 10a1 1 0 0 0 -1 1v.01a1 1 0 0 0 2 0v-.01a1 1 0 0 0 -1 -1m0 -6a1 1 0 0 0 -1 1v3a1 1 0 0 0 2 0v-3a1 1 0 0 0 -1 -1",
        ),
      ]),
    ],
  )
}

/// `messages`
pub fn messages(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.filled_defaults,
    attrs: attrs,
    children: [
      svg.path([
        attribute.attribute(
          "d",
          "M20.901 14.995l-.044 -.006a.4 .4 0 0 1 -.102 -.02l-.045 -.012l-.048 -.017l-.045 -.016l-.043 -.02l-.045 -.022l-.04 -.024l-.044 -.026l-.043 -.032l-.036 -.027a1 1 0 0 1 -.073 -.066l-2.707 -2.707h-6.586a2 2 0 0 1 -2 -2v-6a2 2 0 0 1 2 -2h9a2 2 0 0 1 2 2v10a1 1 0 0 1 -.076 .383l-.02 .043l-.022 .045l-.024 .04l-.026 .044l-.032 .043l-.027 .036a1 1 0 0 1 -.578 .347l-.052 .008l-.044 .006a1 1 0 0 1 -.198 0",
        ),
      ]),
      svg.path([
        attribute.attribute(
          "d",
          "M7 8.999v1.001a4 4 0 0 0 4 4h4v3a2 2 0 0 1 -2 2h-6.586l-2.707 2.707c-.63 .63 -1.707 .184 -1.707 -.707v-10a2 2 0 0 1 2 -2z",
        ),
      ]),
    ],
  )
}

/// `meteor`
pub fn meteor(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.filled_defaults,
    attrs: attrs,
    children: [
      svg.path([
        attribute.attribute(
          "d",
          "M21.874 3.486l-4.174 7.514h3.3c.846 0 1.293 .973 .791 1.612l-.074 .085l-6.9 7.095a7.5 7.5 0 1 1 -10.21 -10.974l7.746 -6.58c.722 -.614 1.814 .028 1.628 .958l-.577 2.879l7.11 -3.95c.88 -.488 1.849 .481 1.36 1.36m-12.374 7.515a3.5 3.5 0 0 0 -3.495 3.308l-.005 .192a3.5 3.5 0 1 0 3.5 -3.5",
        ),
      ]),
    ],
  )
}

/// `michelin-star`
pub fn michelin_star(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.filled_defaults,
    attrs: attrs,
    children: [
      svg.path([
        attribute.attribute(
          "d",
          "M11.81 2c2.018 0 3.478 1.232 3.874 3.129l.016 .089l.172 -.057c.34 -.104 .684 -.16 1.055 -.175l.227 -.005c2.09 0 3.925 1.93 3.925 4.094c0 1.095 -.51 2.087 -1.364 2.835l-.118 .098l.06 .048c.88 .737 1.36 1.605 1.416 2.656l.006 .213c0 2.24 -1.739 4.094 -3.925 4.094c-.445 0 -.923 -.084 -1.374 -.233l-.043 .193c-.395 1.736 -1.806 2.933 -3.662 3.016l-.208 .005c-2.018 0 -3.477 -1.232 -3.873 -3.13l-.03 -.161l-.011 .006a4.1 4.1 0 0 1 -1.26 .243l-.226 .005c-2.09 0 -3.925 -1.93 -3.925 -4.094c0 -1.096 .51 -2.087 1.378 -2.84l.073 -.062l-.03 -.023c-.88 -.737 -1.359 -1.605 -1.415 -2.656l-.006 -.213c0 -2.239 1.74 -4.094 3.925 -4.094c.44 0 .92 .098 1.391 .27l.036 .013l.008 -.048c.331 -1.84 1.776 -3.125 3.7 -3.211z",
        ),
      ]),
    ],
  )
}

/// `mickey`
pub fn mickey(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.filled_defaults,
    attrs: attrs,
    children: [
      svg.path([
        attribute.attribute(
          "d",
          "M18.501 2a4.5 4.5 0 0 1 .878 8.913a8 8 0 1 1 -15.374 3.372l-.005 -.285l.005 -.285a7.991 7.991 0 0 1 .615 -2.803a4.5 4.5 0 0 1 -3.187 -6.348a4.505 4.505 0 0 1 3.596 -2.539l.225 -.018l.281 -.007l.244 .009a4.5 4.5 0 0 1 4.215 4.247a8.001 8.001 0 0 1 4.013 0a4.5 4.5 0 0 1 4.493 -4.256z",
        ),
      ]),
    ],
  )
}

/// `microphone`
pub fn microphone(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.filled_defaults,
    attrs: attrs,
    children: [
      svg.path([
        attribute.attribute(
          "d",
          "M19 9a1 1 0 0 1 1 1a8 8 0 0 1 -6.999 7.938l-.001 2.062h3a1 1 0 0 1 0 2h-8a1 1 0 0 1 0 -2h3v-2.062a8 8 0 0 1 -7 -7.938a1 1 0 1 1 2 0a6 6 0 0 0 12 0a1 1 0 0 1 1 -1m-7 -8a4 4 0 0 1 4 4v5a4 4 0 1 1 -8 0v-5a4 4 0 0 1 4 -4",
        ),
      ]),
    ],
  )
}

/// `microscope`
pub fn microscope(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.filled_defaults,
    attrs: attrs,
    children: [
      svg.path([
        attribute.attribute(
          "d",
          "M15.707 4.293l3 3a1 1 0 0 1 0 1.414l-1.553 1.555a7 7 0 0 1 -.256 9.74l2.102 -.002a1 1 0 0 1 0 2h-14a1 1 0 0 1 0 -2h1v-1a1 1 0 0 1 0 -2h2a1 1 0 0 1 0 2v1h4a5 5 0 0 0 3.737 -8.323l-3.03 3.03a1 1 0 0 1 -1.414 0l-.793 -.792l-.793 .792a1 1 0 1 1 -1.414 -1.414l.792 -.793l-.792 -.793a1 1 0 0 1 0 -1.414l6 -6a1 1 0 0 1 1.414 0m2 -2l3 3a1 1 0 1 1 -1.414 1.414l-3 -3a1 1 0 1 1 1.414 -1.414",
        ),
      ]),
    ],
  )
}

/// `microwave`
pub fn microwave(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.filled_defaults,
    attrs: attrs,
    children: [
      svg.path([
        attribute.attribute(
          "d",
          "M20 5a2 2 0 0 1 2 2v10a2 2 0 0 1 -2 2h-16a2 2 0 0 1 -2 -2v-10a2 2 0 0 1 2 -2zm-6 2h-10v10h10zm4.01 7h-.01a1 1 0 0 0 -.117 1.993l.127 .007a1 1 0 0 0 0 -2m0 -3h-.01a1 1 0 0 0 -.117 1.993l.127 .007a1 1 0 0 0 0 -2m0 -3h-.01a1 1 0 0 0 -.117 1.993l.127 .007a1 1 0 0 0 0 -2",
        ),
      ]),
      svg.path([
        attribute.attribute(
          "d",
          "M5.945 9.668c1.336 -.891 2.274 -.891 3.61 0l-.089 -.056l.04 .017l.146 .064l.095 .044c.378 .171 .533 .23 .674 .255c.133 .023 .186 .005 .336 -.16a1 1 0 1 1 1.486 1.337c-.613 .681 -1.358 .934 -2.164 .794c-.368 -.064 -.621 -.161 -1.158 -.405a10 10 0 0 0 -.306 -.135l-.17 -.091c-.664 -.443 -.726 -.443 -1.39 0a1 1 0 1 1 -1.11 -1.664",
        ),
      ]),
      svg.path([
        attribute.attribute(
          "d",
          "M5.945 12.668c1.336 -.891 2.274 -.891 3.61 0l-.089 -.056l.04 .017l.146 .064l.095 .044c.378 .171 .533 .23 .674 .255c.133 .023 .186 .005 .336 -.16a1 1 0 0 1 1.486 1.337c-.613 .681 -1.358 .934 -2.164 .794c-.368 -.064 -.621 -.161 -1.158 -.405a10 10 0 0 0 -.306 -.135l-.17 -.091c-.664 -.443 -.726 -.443 -1.39 0a1 1 0 1 1 -1.11 -1.664",
        ),
      ]),
    ],
  )
}

/// `military-rank`
pub fn military_rank(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.filled_defaults,
    attrs: attrs,
    children: [
      svg.path([
        attribute.attribute(
          "d",
          "M12.555 2.168l6 4a1 1 0 0 1 .445 .832v12a3 3 0 0 1 -3 3h-8a3 3 0 0 1 -3 -3v-12a1 1 0 0 1 .445 -.832l6 -4a1 1 0 0 1 1.11 0m-.108 12.938a1 1 0 0 0 -.894 0l-2 1a1 1 0 0 0 -.447 1.341l.058 .102a1 1 0 0 0 1.283 .345l1.553 -.776l1.553 .776a1 1 0 0 0 .894 -1.788zm0 -4a1 1 0 0 0 -.894 0l-2 1a1 1 0 0 0 -.447 1.341l.058 .102a1 1 0 0 0 1.283 .345l1.553 -.776l1.553 .776a1 1 0 0 0 .894 -1.788zm0 -4a1 1 0 0 0 -.894 0l-2 1a1 1 0 0 0 -.447 1.341l.058 .102a1 1 0 0 0 1.283 .345l1.553 -.776l1.553 .776a1 1 0 0 0 .894 -1.788z",
        ),
      ]),
    ],
  )
}

/// `milk`
pub fn milk(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.filled_defaults,
    attrs: attrs,
    children: [
      svg.path([
        attribute.attribute(
          "d",
          "M17.799 7l.144 .23a7 7 0 0 1 1.057 3.7v8.07a3 3 0 0 1 -3 3h-8a3 3 0 0 1 -3 -3v-8.071a7 7 0 0 1 1.057 -3.698l.142 -.231zm-5.799 6a3 3 0 0 0 -2.995 2.824l-.005 .176a3 3 0 1 0 3 -3m0 2a1 1 0 1 1 0 2a1 1 0 0 1 0 -2m2 -6h-4a1 1 0 1 0 0 2h4a1 1 0 0 0 0 -2m1 -7a2 2 0 0 1 2 2v1h-10v-1a2 2 0 0 1 2 -2z",
        ),
      ]),
    ],
  )
}

/// `mood-angry`
pub fn mood_angry(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.filled_defaults,
    attrs: attrs,
    children: [
      svg.path([
        attribute.attribute(
          "d",
          "M12 2c5.523 0 10 4.477 10 10s-4.477 10 -10 10a10 10 0 1 1 0 -20m0 12a4.5 4.5 0 0 0 -3.214 1.35a1 1 0 1 0 1.428 1.4a2.5 2.5 0 0 1 3.572 0a1 1 0 0 0 1.428 -1.4a4.5 4.5 0 0 0 -3.214 -1.35m-3.553 -5.895a1 1 0 0 0 -.894 1.788l2 1a1 1 0 0 0 .894 -1.788zm8.447 .447a1 1 0 0 0 -1.341 -.447l-2 1a1 1 0 0 0 .894 1.788l2 -1a1 1 0 0 0 .447 -1.341",
        ),
      ]),
    ],
  )
}

/// `mood-confuzed`
pub fn mood_confuzed(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.filled_defaults,
    attrs: attrs,
    children: [
      svg.path([
        attribute.attribute(
          "d",
          "M17 3.34a10 10 0 1 1 -14.995 8.984l-.005 -.324l.005 -.324a10 10 0 0 1 14.995 -8.336zm-1.43 10.162a11 11 0 0 0 -6.6 1.65a1 1 0 0 0 1.06 1.696a9 9 0 0 1 5.4 -1.35a1 1 0 0 0 .14 -1.996zm-6.56 -4.502l-.127 .007a1 1 0 0 0 0 1.986l.117 .007l.127 -.007a1 1 0 0 0 0 -1.986l-.117 -.007zm6 0l-.127 .007a1 1 0 0 0 0 1.986l.117 .007l.127 -.007a1 1 0 0 0 0 -1.986l-.117 -.007z",
        ),
      ]),
    ],
  )
}

/// `mood-crazy-happy`
pub fn mood_crazy_happy(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.filled_defaults,
    attrs: attrs,
    children: [
      svg.path([
        attribute.attribute(
          "d",
          "M17 3.34a10 10 0 1 1 -15 8.66l.005 -.324a10 10 0 0 1 14.995 -8.336m-1.8 10.946a1 1 0 0 0 -1.414 .014a2.5 2.5 0 0 1 -3.572 0a1 1 0 0 0 -1.428 1.4a4.5 4.5 0 0 0 6.428 0a1 1 0 0 0 -.014 -1.414m-7.493 -6.493a1 1 0 0 0 -1.414 1.414l.792 .793l-.792 .793a1 1 0 0 0 1.414 1.414l.793 -.792l.793 .792a1 1 0 1 0 1.414 -1.414l-.792 -.793l.792 -.793a1 1 0 1 0 -1.414 -1.414l-.793 .792zm7 0a1 1 0 0 0 -1.414 1.414l.792 .793l-.792 .793a1 1 0 0 0 1.414 1.414l.793 -.792l.793 .792a1 1 0 0 0 1.414 -1.414l-.792 -.793l.792 -.793a1 1 0 1 0 -1.414 -1.414l-.793 .792z",
        ),
      ]),
    ],
  )
}

/// `mood-empty`
pub fn mood_empty(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.filled_defaults,
    attrs: attrs,
    children: [
      svg.path([
        attribute.attribute(
          "d",
          "M17 3.34a10 10 0 1 1 -14.995 8.984l-.005 -.324l.005 -.324a10 10 0 0 1 14.995 -8.336zm-2 10.66h-6l-.117 .007a1 1 0 0 0 0 1.986l.117 .007h6l.117 -.007a1 1 0 0 0 0 -1.986l-.117 -.007zm-5.99 -5l-.127 .007a1 1 0 0 0 0 1.986l.117 .007l.127 -.007a1 1 0 0 0 0 -1.986l-.117 -.007zm6 0l-.127 .007a1 1 0 0 0 0 1.986l.117 .007l.127 -.007a1 1 0 0 0 0 -1.986l-.117 -.007z",
        ),
      ]),
    ],
  )
}

/// `mood-happy`
pub fn mood_happy(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.filled_defaults,
    attrs: attrs,
    children: [
      svg.path([
        attribute.attribute(
          "d",
          "M17 3.34a10 10 0 1 1 -14.995 8.984l-.005 -.324l.005 -.324a10 10 0 0 1 14.995 -8.336zm-2 9.66h-6a1 1 0 0 0 -1 1v.05a3.975 3.975 0 0 0 3.777 3.97l.227 .005a4.026 4.026 0 0 0 3.99 -3.79l.006 -.206a1 1 0 0 0 -1 -1.029zm-5.99 -5l-.127 .007a1 1 0 0 0 .117 1.993l.127 -.007a1 1 0 0 0 -.117 -1.993zm6 0l-.127 .007a1 1 0 0 0 .117 1.993l.127 -.007a1 1 0 0 0 -.117 -1.993z",
        ),
      ]),
    ],
  )
}

/// `mood-kid`
pub fn mood_kid(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.filled_defaults,
    attrs: attrs,
    children: [
      svg.path([
        attribute.attribute(
          "d",
          "M17 3.34a10 10 0 1 1 -14.995 8.984l-.005 -.324l.005 -.324a10 10 0 0 1 7.046 -9.232a3 3 0 0 0 2.949 3.556a1 1 0 0 0 0 -2l-.117 -.007a1 1 0 0 1 .117 -1.993c1.726 0 3.453 .447 5 1.34zm-1.8 10.946a1 1 0 0 0 -1.414 .014a2.5 2.5 0 0 1 -3.572 0a1 1 0 0 0 -1.428 1.4a4.5 4.5 0 0 0 6.428 0a1 1 0 0 0 -.014 -1.414zm-6.19 -5.286l-.127 .007a1 1 0 0 0 .117 1.993l.127 -.007a1 1 0 0 0 -.117 -1.993zm6 0l-.127 .007a1 1 0 0 0 .117 1.993l.127 -.007a1 1 0 0 0 -.117 -1.993z",
        ),
      ]),
    ],
  )
}

/// `mood-neutral`
pub fn mood_neutral(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.filled_defaults,
    attrs: attrs,
    children: [
      svg.path([
        attribute.attribute(
          "d",
          "M17 3.34a10 10 0 1 1 -14.995 8.984l-.005 -.324l.005 -.324a10 10 0 0 1 14.995 -8.336zm-7.99 5.66l-.127 .007a1 1 0 0 0 0 1.986l.117 .007l.127 -.007a1 1 0 0 0 0 -1.986l-.117 -.007zm6 0l-.127 .007a1 1 0 0 0 0 1.986l.117 .007l.127 -.007a1 1 0 0 0 0 -1.986l-.117 -.007z",
        ),
      ]),
    ],
  )
}

/// `mood-sad`
pub fn mood_sad(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.filled_defaults,
    attrs: attrs,
    children: [
      svg.path([
        attribute.attribute(
          "d",
          "M17 3.34a10 10 0 1 1 -14.995 8.984l-.005 -.324l.005 -.324a10 10 0 0 1 14.995 -8.336zm-5 9.86a4.5 4.5 0 0 0 -3.214 1.35a1 1 0 1 0 1.428 1.4a2.5 2.5 0 0 1 3.572 0a1 1 0 0 0 1.428 -1.4a4.5 4.5 0 0 0 -3.214 -1.35zm-2.99 -4.2l-.127 .007a1 1 0 0 0 0 1.986l.117 .007l.127 -.007a1 1 0 0 0 0 -1.986l-.117 -.007zm6 0l-.127 .007a1 1 0 0 0 0 1.986l.117 .007l.127 -.007a1 1 0 0 0 0 -1.986l-.117 -.007z",
        ),
      ]),
    ],
  )
}

/// `mood-smile`
pub fn mood_smile(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.filled_defaults,
    attrs: attrs,
    children: [
      svg.path([
        attribute.attribute(
          "d",
          "M17 3.34a10 10 0 1 1 -14.995 8.984l-.005 -.324l.005 -.324a10 10 0 0 1 14.995 -8.336zm-1.8 10.946a1 1 0 0 0 -1.414 .014a2.5 2.5 0 0 1 -3.572 0a1 1 0 0 0 -1.428 1.4a4.5 4.5 0 0 0 6.428 0a1 1 0 0 0 -.014 -1.414zm-6.19 -5.286l-.127 .007a1 1 0 0 0 .117 1.993l.127 -.007a1 1 0 0 0 -.117 -1.993zm6 0l-.127 .007a1 1 0 0 0 .117 1.993l.127 -.007a1 1 0 0 0 -.117 -1.993z",
        ),
      ]),
    ],
  )
}

/// `mood-wrrr`
pub fn mood_wrrr(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.filled_defaults,
    attrs: attrs,
    children: [
      svg.path([
        attribute.attribute(
          "d",
          "M12 2c5.523 0 10 4.477 10 10s-4.477 10 -10 10a10 10 0 1 1 0 -20m3.707 12.293a1 1 0 0 0 -1.262 -.125l-.945 .63l-.945 -.63l-.116 -.066a1 1 0 0 0 -.994 .066l-.945 .63l-.945 -.63a1 1 0 0 0 -1.262 .125l-1 1a1 1 0 0 0 0 1.414l.094 .083a1 1 0 0 0 1.32 -.083l.42 -.42l.818 .545l.116 .066a1 1 0 0 0 .994 -.066l.945 -.63l.945 .63l.116 .066a1 1 0 0 0 .994 -.066l.817 -.545l.42 .42a1 1 0 0 0 1.415 -1.414zm-6.5 -6.5a1 1 0 0 0 -1.414 0l-.083 .094a1 1 0 0 0 .083 1.32l.792 .793l-.792 .793a1 1 0 0 0 1.414 1.414l1.5 -1.5a1 1 0 0 0 0 -1.414zm7 0a1 1 0 0 0 -1.414 0l-1.5 1.5a1 1 0 0 0 0 1.414l1.5 1.5a1 1 0 0 0 1.414 0l.083 -.094a1 1 0 0 0 -.083 -1.32l-.792 -.793l.792 -.793a1 1 0 0 0 0 -1.414",
        ),
      ]),
    ],
  )
}

/// `moon`
pub fn moon(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.filled_defaults,
    attrs: attrs,
    children: [
      svg.path([
        attribute.attribute(
          "d",
          "M12 1.992a10 10 0 1 0 9.236 13.838c.341 -.82 -.476 -1.644 -1.298 -1.31a6.5 6.5 0 0 1 -6.864 -10.787l.077 -.08c.551 -.63 .113 -1.653 -.758 -1.653h-.266l-.068 -.006l-.06 -.002z",
        ),
      ]),
    ],
  )
}

/// `motorbike`
pub fn motorbike(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.filled_defaults,
    attrs: attrs,
    children: [
      svg.path([
        attribute.attribute(
          "d",
          "M15 5a1 1 0 0 1 .894 .553l3.225 6.449l.08 .003a4 4 0 1 1 -4.199 3.995l.005 -.2a4 4 0 0 1 2.111 -3.33l-.557 -1.115l-3.352 3.352a1 1 0 0 1 -.707 .293h-3.626q .124 .481 .126 1a4 4 0 1 1 -8 0l.005 -.2a4 4 0 0 1 6.33 -3.049l1.749 -1.751h-3.084a1 1 0 0 1 -.993 -.883l-.007 -.117a1 1 0 0 1 1 -1h9.381l-1 -2h-1.381a1 1 0 0 1 -.993 -.883l-.007 -.117a1 1 0 0 1 1 -1z",
        ),
      ]),
    ],
  )
}

/// `mountain`
pub fn mountain(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.filled_defaults,
    attrs: attrs,
    children: [
      svg.path([
        attribute.attribute(
          "d",
          "M6.18 10.95l2.54 3.175l.084 .093a1 1 0 0 0 1.403 -.01l1.637 -1.638l1.324 1.985a1 1 0 0 0 1.457 .226l3.632 -2.906l3.647 7.697a1 1 0 0 1 -.904 1.428h-18a1 1 0 0 1 -.904 -1.428zm5.82 -7.878a3.3 3.3 0 0 1 2.983 1.888l2.394 5.057l-3.15 2.52l-1.395 -2.092l-.075 -.099a1 1 0 0 0 -1.464 -.053l-1.711 1.709l-1.301 -1.627l-1.151 -1.435l1.888 -3.98a3.3 3.3 0 0 1 2.982 -1.888",
        ),
      ]),
    ],
  )
}

/// `mouse`
pub fn mouse(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.filled_defaults,
    attrs: attrs,
    children: [
      svg.path([
        attribute.attribute(
          "d",
          "M14 2a5 5 0 0 1 5 5v10a5 5 0 0 1 -5 5h-4a5 5 0 0 1 -5 -5v-10a5 5 0 0 1 5 -5zm-2 4a1 1 0 0 0 -1 1v4l.007 .117a1 1 0 0 0 1.993 -.117v-4l-.007 -.117a1 1 0 0 0 -.993 -.883z",
        ),
      ]),
    ],
  )
}

/// `mug`
pub fn mug(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.filled_defaults,
    attrs: attrs,
    children: [
      svg.path([
        attribute.attribute(
          "d",
          "M3.903 4.008l.183 -.008h10.828a2.08 2.08 0 0 1 2.086 2.077v.923h1.5c1.917 0 3.5 1.477 3.5 3.333v2.334c0 1.856 -1.583 3.333 -3.5 3.333h-1.663a5.33 5.33 0 0 1 -5.17 4h-4.334c-2.944 0 -5.333 -2.375 -5.333 -5.308v-8.618a2.08 2.08 0 0 1 1.903 -2.066m13.097 9.992h1.5c.843 0 1.5 -.613 1.5 -1.333v-2.334c0 -.72 -.657 -1.333 -1.5 -1.333h-1.5z",
        ),
      ]),
    ],
  )
}

/// `mushroom`
pub fn mushroom(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.filled_defaults,
    attrs: attrs,
    children: [
      svg.path([
        attribute.attribute(
          "d",
          "M15 15v4a3 3 0 0 1 -5.995 .176l-.005 -.176v-4h6zm-10.1 -2a1.9 1.9 0 0 1 -1.894 -1.752l-.006 -.148c0 -5.023 4.027 -9.1 9 -9.1s9 4.077 9 9.1a1.9 1.9 0 0 1 -1.752 1.894l-.148 .006h-14.2z",
        ),
      ]),
    ],
  )
}
