//// tabler · filled · shard "v". GENERATED by gg_icon_gen — do not hand-edit.

import gg_icon/icon
import gg_icons_tabler/internal
import lustre/attribute.{type Attribute}
import lustre/element.{type Element}
import lustre/element/svg

/// `versions`
pub fn versions(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.filled_defaults,
    attrs: attrs,
    children: [
      svg.path([
        attribute.attribute(
          "d",
          "M18 4h-6a3 3 0 0 0 -3 3v10a3 3 0 0 0 3 3h6a3 3 0 0 0 3 -3v-10a3 3 0 0 0 -3 -3z",
        ),
      ]),
      svg.path([
        attribute.attribute(
          "d",
          "M7 6a1 1 0 0 1 .993 .883l.007 .117v10a1 1 0 0 1 -1.993 .117l-.007 -.117v-10a1 1 0 0 1 1 -1z",
        ),
      ]),
      svg.path([
        attribute.attribute(
          "d",
          "M4 7a1 1 0 0 1 .993 .883l.007 .117v8a1 1 0 0 1 -1.993 .117l-.007 -.117v-8a1 1 0 0 1 1 -1z",
        ),
      ]),
    ],
  )
}

/// `video`
pub fn video(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.filled_defaults,
    attrs: attrs,
    children: [
      svg.path([
        attribute.attribute(
          "d",
          "M20.117 7.625a1 1 0 0 0 -.564 .1l-4.553 2.275v4l4.553 2.275a1 1 0 0 0 1.447 -.892v-6.766a1 1 0 0 0 -.883 -.992z",
        ),
      ]),
      svg.path([
        attribute.attribute(
          "d",
          "M5 5c-1.645 0 -3 1.355 -3 3v8c0 1.645 1.355 3 3 3h8c1.645 0 3 -1.355 3 -3v-8c0 -1.645 -1.355 -3 -3 -3z",
        ),
      ]),
    ],
  )
}

/// `video-minus`
pub fn video_minus(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.filled_defaults,
    attrs: attrs,
    children: [
      svg.path([
        attribute.attribute(
          "d",
          "M13 5a3 3 0 0 1 3 3v.381l3.106 -1.552a2 2 0 0 1 2.894 1.789v6.765a2 2 0 0 1 -2.894 1.787l-3.106 -1.552v.382a3 3 0 0 1 -3 3h-8a3 3 0 0 1 -3 -3v-8a3 3 0 0 1 3 -3zm-2 6h-4a1 1 0 0 0 0 2h4a1 1 0 0 0 0 -2",
        ),
      ]),
    ],
  )
}

/// `video-plus`
pub fn video_plus(attrs: List(Attribute(msg))) -> Element(msg) {
  icon.svg(
    view_box: "0 0 24 24",
    defaults: internal.filled_defaults,
    attrs: attrs,
    children: [
      svg.path([
        attribute.attribute(
          "d",
          "M13 5a3 3 0 0 1 3 3v.381l3.106 -1.552a2 2 0 0 1 2.894 1.789v6.765a2 2 0 0 1 -2.894 1.787l-3.106 -1.552v.382a3 3 0 0 1 -3 3h-8a3 3 0 0 1 -3 -3v-8a3 3 0 0 1 3 -3zm-4 4a1 1 0 0 0 -1 1v1h-1a1 1 0 0 0 0 2h1v1a1 1 0 0 0 2 0v-1h1a1 1 0 0 0 0 -2h-1v-1a1 1 0 0 0 -1 -1",
        ),
      ]),
    ],
  )
}
