//// Internal — per-variant SVG defaults baked into the generated shards.
//// GENERATED by gg_icon_gen — do not hand-edit.

/// Baked onto every `outline` icon's `<svg>`.
pub const outline_defaults = [
  #("fill", "none"),
  #("stroke", "currentColor"),
  #("stroke-width", "2"),
  #("stroke-linecap", "round"),
  #("stroke-linejoin", "round"),
]

/// Baked onto every `filled` icon's `<svg>`.
pub const filled_defaults = [#("fill", "currentColor")]
